Repository debionetwork/debio-backend, pull requests merged in 2021-11, with the labels that each got.

#93 feat: endpoint to synchronize events.
  file/lastblock.txt
  package-lock.json
  src/cloud-storage/cloud-storage.controller.ts
  src/cloud-storage/cloud-storage.module.ts
  src/cloud-storage/dto/data-staking.dto.ts
  src/cloud-storage/models/data-staking-sync-events.entity.ts
Labels: enhancement

#94 feat: add action params for gcs signed url.
  package-lock.json
  src/cloud-storage/cloud-storage.controller.ts
Labels: enhancement

#95 feat: changed event data field to filename.
  src/cloud-storage/cloud-storage.controller.ts
  src/cloud-storage/dto/data-staking.dto.ts
  src/cloud-storage/models/data-staking-sync-events.entity.ts
Labels: enhancement

#104 feat: mail after lab registered event.
  nest-cli.json
  package-lock.json
  package.json
  src/app.module.ts
  src/common/common.module.ts
  src/common/mailer/mailer.manager.ts
  src/common/mailer/mailer.module.ts
  src/common/mailer/models/customer-staking-request-service.model.ts
  src/common/mailer/models/lab-register.model/certification.ts
  src/common/mailer/models/lab-register.model/lab-register.model.ts
  src/common/mailer/models/lab-register.model/service.ts
  src/common/mailer/templates/customer-staking-request-service.hbs
  src/common/mailer/templates/lab-register.hbs
  src/common/polkadot-provider/models/certifications/certification-info.ts
  src/common/polkadot-provider/models/certifications/index.ts
  src/common/polkadot-provider/models/labs/index.ts
  src/common/polkadot-provider/models/labs/lab-info.ts
  src/common/polkadot-provider/models/labs/lab-verification-status.ts
  src/common/polkadot-provider/models/services/expected-duration.ts
  src/common/polkadot-provider/models/services/index.ts
  src/common/polkadot-provider/models/services/price-by-currency.ts
  src/common/polkadot-provider/models/services/price.ts
  src/common/polkadot-provider/models/services/service-flow.ts
  src/common/polkadot-provider/models/services/service-info.ts
  src/common/polkadot-provider/query/labs/certifications.ts
  src/common/polkadot-provider/query/labs/index.ts
  src/common/polkadot-provider/query/services.ts
  src/mail/mail.service.ts
  src/substrate/geneticTestingEvent.ts
  src/substrate/orderEvent.ts
  src/substrate/serviceEvent.ts
  src/substrate/substrate.module.ts
  src/substrate/substrate.service.ts
  src/substrate/substrateTypes.json
Labels: enhancement

#113 ci: update Dockerfile
  .dockerignore
  .maintain/docker/Dockerfile
Labels: CI

#117 ci: improve env deploy
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: CI

#120 get env from google secret manager
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: CI

#122 ci: removed unuse env
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: CI

#124 ci: used swagger env dafault value
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: CI

#126 ci: fix deployment
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: CI

#128 changed google service account value path
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: CI

#129 ci: remove unused code
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: CI

#130 change .env injected
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: CI

#132 ci: improve main automation
  .github/workflows/main.yml
Labels: CI

#133 ci: improve staging env secret
  .github/workflows/alpha.yml
Labels: CI

#136 ci: add new env
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: CI

#138 ci: separate staging environment
  .github/workflows/alpha.yml
Labels: CI

#140 ci: improve env
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: CI

#141 ci: update .dockerignore
  .dockerignore
Labels: CI

#143 add helm charts
  .maintain/kubernetes/.helmignore
  .maintain/kubernetes/Chart.yaml
  .maintain/kubernetes/templates/_helpers.tpl
  .maintain/kubernetes/templates/deployment.yaml
  .maintain/kubernetes/templates/hpa.yaml
  .maintain/kubernetes/templates/ingress.yaml
  .maintain/kubernetes/templates/secrets.yaml
  .maintain/kubernetes/templates/service.yaml
  .maintain/kubernetes/templates/serviceaccount.yaml
  .maintain/kubernetes/templates/tests/test-connection.yaml
  .maintain/kubernetes/values.yaml
Labels: CI

#144 ci: fix spacing
  .github/workflows/main.yml
Labels: CI

#149 added swagger value for deployment staging
  .github/workflows/alpha.yml
Labels: CI

#152 refactor: bounty endpoint.
  file/lastblock.txt
  src/app.module.ts
  src/bounty/bounty.controller.spec.ts
  src/bounty/bounty.controller.ts
  src/bounty/bounty.module.ts
  src/bounty/bounty.service.spec.ts
  src/bounty/bounty.service.ts
  src/bounty/dto/create-bounty.dto.ts
  src/bounty/dto/data-staking.dto.ts
  src/bounty/models/bounty.entity.ts
  src/bounty/models/data-staking-events.entity.ts
  src/cloud-storage/cloud-storage.controller.ts
  src/cloud-storage/cloud-storage.module.ts
  src/cloud-storage/dto/data-staking.dto.ts
  src/cloud-storage/models/data-staking-sync-events.entity.ts
Labels: refactor

#154 test: moved e2e tests folder.
  package.json
  test/e2e/app.e2e-spec.ts
  test/e2e/data_bounty.e2e-spec.ts
  test/e2e/emr.e2e-spec.ts
  test/e2e/jest-e2e.json
  test/e2e/location.e2e-spec.ts
  test/e2e/rating.e2e-spec.ts
  test/e2e/service-categoty.e2e-spec.ts
  test/e2e/service-request.e2e-spec.ts
  test/e2e/substrate-indexed-lab.e2e-spec.ts
  test/e2e/substrate-indexed-order.e2e-spec.ts
  test/e2e/substrate-indexed-service.e2e-spec.ts
  test/e2e/substrate.e2e-spec.ts
Labels: tests

#155 refactor: datetime and create proxy.
  package.json
  src/cloud-storage/cloud-storage.controller.ts
  src/cloud-storage/cloud-storage.module.ts
  src/common/date-time/date-time.module.ts
  src/common/date-time/date-time.proxy.ts
  src/rating/rating.controller.spec.ts
  test/unit/category/emr/emr.controller.spec.ts
  test/unit/category/emr/emr.service.spec.ts
  test/unit/category/service/service-category.controller.spec.ts
  test/unit/category/service/service-category.service.spec.ts
  test/unit/jest-unit.json
  test/unit/mock.ts
Labels: refactor, tests
