Repository debionetwork/debio-backend, pull requests merged in 2021-12, with the labels that each got.

#157 ci: renamed testnet env
  .github/workflows/beta.yml
Labels: CI

#162 ci: fixed automation name
  .github/workflows/beta.yml
Labels: CI

#166 ci: add CORS and ingress basic-auth
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: CI

#167 ci: fix mainnet env
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: CI

#168 ci: update node version pr automation
  .github/workflows/pull-request.yml
Labels: CI

#165 Enhance binding
  file/lastblock.txt
  package-lock.json
  src/ethereum-indexed-data/service-request/service-request.controller.ts
  src/ethereum-indexed-data/service-request/service-request.service.ts
  src/reward/reward.service.ts
  src/substrate-indexed-data/labs/lab.controller.ts
  src/substrate-indexed-data/labs/lab.service.ts
  src/substrate-indexed-data/orders/order.controller.ts
  src/substrate-indexed-data/orders/order.service.ts
  src/substrate-indexed-data/services/service.service.ts
  src/substrate/orderEvent.ts
  src/substrate/substrate.controller.ts
Labels: enhancement

#169 ci: improve cors, limit-rps, ingress basic-auth
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: CI

#171 ci: add ingress basic-auth dev
  .github/workflows/beta.yml
  .github/workflows/main.yml
Labels: CI

#175 ci: improve env
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: CI

#172 tests: lab and service indexer unit tests.
  src/bounty/bounty.controller.ts
  src/substrate-indexed-data/labs/lab.service.ts
  src/substrate-indexed-data/services/service.service.ts
  test/unit/bounty/bounty.controller.spec.ts
  test/unit/cloud-storage/cloud-storage.controller.spec.ts
  test/unit/mock.ts
  test/unit/substrate-indexed-data/labs/lab.controller.spec.ts
  test/unit/substrate-indexed-data/labs/lab.service.spec.ts
  test/unit/substrate-indexed-data/services/service.controller.spec.ts
  test/unit/substrate-indexed-data/services/service.service.spec.ts
  test/unit/verification/verification.controller.spec.ts
Labels: enhancement, tests

#178 feat: healthcheck and security.
  file/lastblock.txt
  package-lock.json
  package.json
  src/app.module.ts
  src/health/health.controller.spec.ts
  src/health/health.controller.ts
  src/health/health.module.ts
  src/main.ts
  test/unit/verification/verification.controller.spec.ts
Labels: enhancement

#177 Url redis
  package-lock.json
  package.json
  src/app.module.ts
  src/dbio-balance/dbio_balance.controller.ts
  src/dbio-balance/dbio_balance.module.ts
  src/dbio-balance/dbio_balance.service.ts
  src/dbio-balance/dto/dbio_balance.dto.ts
  src/dbio-balance/models/dbio_balance.entity.ts
  src/debio-conversion/debio-conversion.module.ts
  src/debio-conversion/debio-conversion.service.ts
  src/ethereum-indexed-data/ethereum-indexed-data.module.ts
  src/ethereum-indexed-data/service-request/service-request.service.ts
  src/reward/reward.module.ts
  src/substrate/geneticTestingEvent.ts
  src/substrate/orderEvent.ts
  src/substrate/substrate.module.ts
  src/substrate/substrate.service.ts
Labels: bug, enhancement

#163 Email flow
  .vscode/settings.json
  file/lastblock.txt
  src/common/mailer/mailer.controller.ts
  src/common/mailer/mailer.manager.ts
  src/common/mailer/mailer.module.ts
  src/common/mailer/models/lab-register.model/service.ts
  src/common/mailer/templates/customer-staking-request-service.hbs
  src/common/mailer/templates/lab-register.hbs
  src/common/polkadot-provider/models/certifications/certification-info.ts
  src/common/polkadot-provider/models/certifications/index.ts
  src/common/polkadot-provider/models/labs/index.ts
  src/common/polkadot-provider/models/labs/lab-info.ts
  src/common/polkadot-provider/models/services/expected-duration.ts
  src/common/polkadot-provider/models/services/index.ts
  src/common/polkadot-provider/models/services/price-by-currency.ts
  src/common/polkadot-provider/models/services/service-info.ts
  src/common/polkadot-provider/query/labs/certifications.ts
  src/common/polkadot-provider/query/services.ts
  src/substrate/serviceEvent.ts
  src/substrate/serviceRequestEvent.ts
Labels: enhancement, refactor

#173 Schedule unstaked
  package-lock.json
  package.json
  src/app.module.ts
  src/schedulers/schedulers.module.ts
  src/schedulers/unstaked/unstaked.service.spec.ts
  src/schedulers/unstaked/unstaked.service.ts
  src/substrate/substrate.service.ts
  test/unit/mock.ts
Labels: enhancement

#180 test: mailer manager unit tests.
  .gitignore
  .vscode/settings.json
  package-lock.json
  package.json
  src/common/index.ts
  src/common/mailer/mailer.manager.ts
  src/common/mailer/mailer.module.ts
  src/common/mailer/models/lab-register.model/service.ts
  src/common/polkadot-provider/models/services/service-info.ts
  src/substrate/serviceEvent.ts
  src/substrate/serviceRequestEvent.ts
  src/substrate/substrate.module.ts
  src/substrate/substrate.service.ts
  test/unit/common/mailer/mailer.manager.spec.ts
  test/unit/common/mailer/mailer.mock.data.ts
  test/unit/mock.ts
Labels: enhancement, refactor, tests

#179 ci: add new env
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
Labels: CI

#181 ci: improve nginx ingress path
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: CI

#182 ci: add ingress cors-allow-headers
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
Labels: CI

#185 ci: use gcr private repository
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: CI

#186 ci: fix image repository
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: CI

#188 ci: improve github workflows
  .debio.pipeline.yml
  .dockerignore
  .github/pull_request_template.md
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/builder.yml
  .github/workflows/deploy.yml
  .github/workflows/main.yml
  .github/workflows/publish-draft-release-candidate.yml
  .github/workflows/publish-draft-release.yml
  .github/workflows/release.yml
  .maintain/kubernetes/.helmignore
  .maintain/kubernetes/Chart.yaml
  .maintain/kubernetes/templates/_helpers.tpl
  .maintain/kubernetes/templates/deployment.yaml
  .maintain/kubernetes/templates/hpa.yaml
  .maintain/kubernetes/templates/ingress.yaml
  .maintain/kubernetes/templates/secrets.yaml
  .maintain/kubernetes/templates/service.yaml
  .maintain/kubernetes/templates/serviceaccount.yaml
  .maintain/kubernetes/templates/tests/test-connection.yaml
  .maintain/kubernetes/values.yaml
  Dockerfile
  build-dev.sh
  reload-dev.sh
Labels: CI

#189 feat: mailer scheduler for future update.
  src/schedulers/mailer/mailer.service.spec.ts
  src/schedulers/mailer/mailer.service.ts
Labels: enhancement

#190 ci: add new env and enable autoscaling
  .github/workflows/deploy.yml
Labels: CI

#191 ci: fix mainnet deployment
  .github/workflows/deploy.yml
Labels: CI

#192 ci: cleaning
  .github/workflows/deploy.yml
Labels: CI

#193 ci: improve github action workflows
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/builder.yml
  .github/workflows/deploy.yml
  .github/workflows/main.yml
  .github/workflows/publish-draft-release-candidate.yml
  .github/workflows/publish-draft-release.yml
  .github/workflows/release.yml
Labels: CI

#194 ci: improve github workflows
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: CI
