Repository debionetwork/debio-backend, pull requests merged in 2022-06, with the labels that each got.

#375 fix : fix nonce and gasPrice in orderFulfilled
  package-lock.json
  package.json
  src/common/modules/escrow/escrow.service.ts
  src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
  test/unit/common/modules/escrow/escrow.service.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.spec.ts
Labels: fix

#345 feat: Doc swagger description
  src/endpoints/category/emr/emr.controller.ts
  src/endpoints/category/emr/models/response.ts
  src/endpoints/category/service/models/response.ts
  src/endpoints/category/service/service-category.controller.ts
  src/endpoints/category/specialization/models/response.ts
  src/endpoints/category/specialization/specialization.controller.ts
  src/endpoints/cloud-storage/cloud-storage.controller.ts
  src/endpoints/email/email.controller.ts
  src/endpoints/location/location.controller.ts
  src/endpoints/location/models/response.ts
  src/endpoints/notification/models/response.ts
  src/endpoints/notification/notification.controller.ts
  src/endpoints/rating/models/response.ts
  src/endpoints/rating/rating.controller.ts
  src/endpoints/substrate-endpoint/models/response.ts
  src/endpoints/substrate-endpoint/services/genetic-analysis.service.ts
  src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
  src/endpoints/transaction/transaction.controller.ts
  src/endpoints/verification/verification.controller.ts
  test/unit/endpoints/substrate-endpoint/services/genetic-analysis.service.spec.ts
Labels: document

#358 feat: Staking amount excess and partial notification and listener
  src/listeners/substrate-listener/commands/service-request/index.ts
  src/listeners/substrate-listener/commands/service-request/service-request-excess/service-request-excess.command.ts
  src/listeners/substrate-listener/commands/service-request/service-request-excess/service-request-excess.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-partial/service-request-partial.command.ts
  src/listeners/substrate-listener/commands/service-request/service-request-partial/service-request-partial.handler.ts
  src/listeners/substrate-listener/substrate-listener.handler.ts
Labels: feature, test

#376 enhance: remove service flow from substrate/labs endpoint
  src/endpoints/substrate-endpoint/services/lab.service.ts
  src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
  test/unit/endpoints/substrate-endpoint/services/lab.service.spec.ts
  test/unit/endpoints/substrate-endpoint/substrate-endpoint.controller.spec.ts
Labels: improvement

#377 feat: add unique id in logger terminal
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-cancelled/genetic-analysis-order-cancelled.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-fulfilled/genetic-analysis-order-fulfilled.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-paid/genetic-analysis-order-paid.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-refunded/genetic-analysis-order-refunded.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysys-order-created/genetic-analysis-order-created.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis/genetic-analysis-rejected/genetic-analysis-rejected.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis/genetic-analysis-resultready/genetic-analysis-result-ready.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysts/genetic-analyst-staked/genetic-analyst-staked.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysts/genetic-analyst-unstake/genetic-analyst-unstaked.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysts/genetic-analyst-verification-status/genetic-analyst-verification-status.handler.ts
  src/listeners/substrate-listener/commands/genetic-testing/data-staked/data-staked.handler.ts
  src/listeners/substrate-listener/commands/labs/registered/lab-registered.handler.ts
  src/listeners/substrate-listener/commands/labs/retrieve-unstake-amount/retrieve-unstake-amount.handler.ts
  src/listeners/substrate-listener/commands/labs/stake-successfull/stake-successful.handler.ts
  src/listeners/substrate-listener/commands/labs/unstake-successfull/unstaked-successful.handler.ts
  src/listeners/substrate-listener/commands/orders/order-cancelled/order-cancelled.handler.ts
  src/listeners/substrate-listener/commands/orders/order-created/order-created.handler.ts
  src/listeners/substrate-listener/commands/orders/order-failed/order-failed.handler.ts
  src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
  src/listeners/substrate-listener/commands/orders/order-paid/order-paid.handler.ts
  src/listeners/substrate-listener/commands/orders/order-refunded/order-refunded.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-created/service-request-created.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-unstaked/service-request-unstaked.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-waiting-for-unstaked/service-request-waiting-for-unstaked.handler.ts
  src/listeners/substrate-listener/commands/services/service-created/service-created.handler.ts
Labels: improvement

#364 feat : notification Customer - Request Rejected
  src/listeners/substrate-listener/commands/genetic-analysis/genetic-analysis-rejected/genetic-analysis-rejected.handler.ts
  test/unit/listeners/substrate-listener/commands/genetic-analysis/genetic-analysis-rejected/genetic-analysis-rejected.handler.spec.ts
Labels: feature, test

#357 feat : notification - New Order, Receive QC Payment, Receive Total Payment
  src/listeners/substrate-listener/commands/orders/order-created/order-created.handler.ts
  src/listeners/substrate-listener/commands/orders/order-failed/order-failed.handler.ts
  src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
  src/listeners/substrate-listener/commands/orders/order-paid/order-paid.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-created/service-request-created.handler.ts
  test/unit/listeners/substrate-listener/commands/orders/order-failed/order-failed.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-paid/order-paid.handler.spec.ts
Labels: feature

#378 ci: improve dockerfile and deployment resource request
  .github/workflows/deploy.yml
  .maintain/docker/Dockerfile
Labels: ci

#353 feat : notification User - Wallet Binding
  src/endpoints/substrate-endpoint/dto/wallet-binding.dto.ts
  src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
  test/e2e/elasticsearch-fixture.ts
  test/e2e/endpoints/substrate-endpoint.spec.ts
  test/unit/endpoints/substrate-endpoint/substrate-endpoint.controller.spec.ts
Labels: feature

#367 feat : notificaiton Customer - Test Result Ready + UT
  src/listeners/substrate-listener/commands/genetic-testing/dna-sample-result-ready/dna-sample-result-ready.command.ts
  src/listeners/substrate-listener/commands/genetic-testing/dna-sample-result-ready/dna-sample-result-ready.handler.ts
  src/listeners/substrate-listener/commands/genetic-testing/index.ts
  test/unit/listeners/substrate-listener/commands/genetic-testing/dna-sample-result-ready/dna-sample-result-ready.command.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-testing/dna-sample-result-ready/dna-sample-result-ready.handler.spec.ts
  test/unit/mock.ts
Labels: feature, test

#368 feat : notification Customer - Service Available
  src/listeners/substrate-listener/commands/service-request/index.ts
  src/listeners/substrate-listener/commands/service-request/service-request-claimed/service-request-claimed.command.ts
  src/listeners/substrate-listener/commands/service-request/service-request-claimed/service-request-claimed.handler.ts
  src/listeners/substrate-listener/substrate-listener.handler.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-claimed/service-request-claimed.command.spec.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-claimed/service-request-claimed.handler.spec.ts
Labels: feature, test

#369 feat : notification Customer - Service Fee Refunded
  src/listeners/substrate-listener/commands/orders/order-refunded/order-refunded.handler.ts
  test/unit/listeners/substrate-listener/commands/orders/order-refunded/order-refunded.handler.spec.ts
Labels: feature, test

#372 feat : notification GA - Receive Payment
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-fulfilled/genetic-analysis-order-fulfilled.handler.ts
  test/unit/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-fulfilled/genetic-analysis-order-fulfilled.command.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-fulfilled/genetic-analysis-order-fulfilled.handler.spec.ts
Labels: feature, test

#373 feat : notification GA - Submit account registration and verification
  src/endpoints/verification/verification.service.ts
  test/unit/endpoints/verification/verification.service.spec.ts
Labels: feature, test

#379 feat: notification GA - Add New Service + UT
  package.json
  src/listeners/substrate-listener/commands/genetic-analyst-services/genetic-analyst-service-created/genetic-analyst-service-created.command.ts
  src/listeners/substrate-listener/commands/genetic-analyst-services/genetic-analyst-service-created/genetic-analyst-service-created.handler.ts
  src/listeners/substrate-listener/commands/genetic-analyst-services/index.ts
  src/listeners/substrate-listener/commands/service-request/service-request-created/service-request-created.handler.ts
  src/listeners/substrate-listener/substrate-listener.handler.ts
  src/listeners/substrate-listener/substrate-listener.module.ts
  test/unit/listeners/substrate-listener/commands/genetic-analyst-services/genetic-analyst-service-created/genetic-analyst-service-created.command.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analyst-services/genetic-analyst-service-created/genetic-analyst-service-created.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analyst/genetic-analyst-verification-status/genetic-analyst-verification-status.command.spec.ts
  test/unit/mock.ts
Labels: feature, test

#352 feat : Notification Lab - Reward from Completing Req Test from Service Requested
  src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
Labels: feature

#348 feat : Backend Notification Lab - Add New Service
  src/listeners/substrate-listener/commands/services/service-created/service-created.handler.ts
  test/unit/listeners/substrate-listener/commands/services/service-created/service-created.handler.spec.ts
Labels: feature

#371 feat : notification Customer - Sample Rejected (QC Failed)
  package-lock.json
  src/endpoints/verification/verification.module.ts
  src/endpoints/verification/verification.service.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-fulfilled/genetic-analysis-order-fulfilled.handler.ts
  src/listeners/substrate-listener/commands/genetic-testing/dna-sample-rejected/dna-sample-rejected.command.ts
  src/listeners/substrate-listener/commands/genetic-testing/dna-sample-rejected/dna-sample-rejected.handler.ts
  src/listeners/substrate-listener/commands/genetic-testing/index.ts
  src/listeners/substrate-listener/substrate-listener.handler.ts
  test/e2e/elasticsearch-fixture.ts
  test/mocks/models/genetic-analysts/genetic-analysis-orders.mock.ts
  test/unit/endpoints/verification/verification.service.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-testing/dna-sample-rejected/dna-sample-rejected.command.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-testing/dna-sample-rejected/dna-sample-rejected.handler.spec.ts
Labels: fix, feature, test

#370 feat : notification Customer - Stake Amount Refunded
  package-lock.json
  src/listeners/substrate-listener/commands/service-request/index.ts
  src/listeners/substrate-listener/commands/service-request/service-request-staking-amount-refunded/service-request-staking-amount-refunded.command.ts
  src/listeners/substrate-listener/commands/service-request/service-request-staking-amount-refunded/service-request-staking-amount-refunded.handler.ts
  src/listeners/substrate-listener/substrate-listener.handler.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-staking-amount-refunded/service-request-staking-amount-refunded.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-staking-amount-refunded/service-request-staking-amount-refunded.spec.ts
Labels: fix, feature, test

#347 feat : Back End Notification Lab Account Verification
  package-lock.json
  src/endpoints/verification/verification.controller.ts
  src/endpoints/verification/verification.service.ts
  src/listeners/substrate-listener/commands/orders/order-failed/order-failed.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-excess/service-request-excess.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-partial/service-request-partial.handler.ts
  test/e2e/endpoints/rating.spec.ts
  test/unit/common/modules/reward/reward.service.spec.ts
  test/unit/endpoints/verification/verification.controller.spec.ts
  test/unit/endpoints/verification/verification.service.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-failed/order-failed.handler.spec.ts
  test/unit/listeners/substrate-listener/substrate-listener.handler.spec.ts
Labels: fix, feature

#380 ci: add new env
  .github/workflows/deploy.yml
Labels: ci

#386 Notification
  .github/workflows/tester.yml
  package-lock.json
  package.json
  src/common/modules/transaction-logging/transaction-logging.service.ts
  src/endpoints/bounty/bounty.controller.ts
  src/endpoints/bounty/bounty.module.ts
  src/endpoints/cloud-storage/cloud-storage.controller.ts
  src/endpoints/cloud-storage/cloud-storage.module.ts
  src/endpoints/health/health.controller.ts
  src/endpoints/location/city.service.ts
  src/endpoints/verification/verification.service.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-refunded/genetic-analysis-order-refunded.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysys-order-created/genetic-analysis-order-created.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis/genetic-analysis-resultready/genetic-analysis-result-ready.handler.ts
  test/e2e/config.ts
  test/e2e/endpoints/bounty.spec.ts
  test/e2e/endpoints/cloud-storage.spec.ts
  test/unit/common/modules/transaction-logging/transaction-logging.service.spec.ts
  test/unit/endpoints/bounty/bounty.controller.spec.ts
  test/unit/endpoints/cloud-storage/cloud-storage.controller.spec.ts
  test/unit/endpoints/health/health.controller.spec.ts
  test/unit/endpoints/location/city.service.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-created/genetic-analysis-order-created.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-refunded/genetic-analysis-order-refunded.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analysis/geneticn-analysis-result-ready/genetic-analysis-result-ready.handler.spec.ts
  test/unit/mock.ts
Labels: feature, test

#384 fix: mailer integration test & wallet binding
  package-lock.json
  package.json
  src/common/modules/mailer/mailer.manager.ts
  src/common/modules/transaction-logging/models/transaction-request.entity.ts
  src/common/modules/transaction-logging/transaction-logging.service.ts
  src/endpoints/bounty/bounty.controller.ts
  src/endpoints/location/city.service.ts
  src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
  test/e2e/fixture.ts
  test/unit/common/modules/mailer/mailer.manager.spec.ts
  test/unit/common/modules/transaction-logging/transaction-logging.service.spec.ts
  test/unit/endpoints/location/city.service.spec.ts
  test/unit/endpoints/transaction/transaction.controller.spec.ts
  test/unit/endpoints/transaction/transaction.service.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-cancelled/genetic-analysis-order-cancelled.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-created/genetic-analysis-order-created.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-fulfilled/genetic-analysis-order-fulfilled.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-paid/genetic-analysis-order-paid.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-refunded/genetic-analysis-order-refunded.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analyst/genetic-analyst-staked/genetic-analyst-staked.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analyst/genetic-analyst-unstaked/genetic-analyst-unstaked.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analyst/genetic-analyst-verification-status/genetic-analyst-verification-status.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/lab/lab-registered/lab-registered.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/lab/lab-retrieve-unstaked-amount/lab-retrieve-unstaked-amount.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/lab/lab-staked-successful/lab-staked-successful.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/lab/lab-unstaked-successful/lab-unstaked-successful.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-cancelled/order-cancelled.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-created/order-created.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-paid/order-paid.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-refunded/order-refunded.handler.spec.ts
Labels: fix

#388 feat: notification ga
  src/endpoints/verification/verification.service.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-fulfilled/genetic-analysis-order-fulfilled.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-paid/genetic-analysis-order-paid.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-refunded/genetic-analysis-order-refunded.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysys-order-created/genetic-analysis-order-created.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis/genetic-analysis-rejected/genetic-analysis-rejected.handler.ts
  src/listeners/substrate-listener/commands/genetic-analyst-services/genetic-analyst-service-created/genetic-analyst-service-created.handler.ts
  src/listeners/substrate-listener/commands/labs/registered/lab-registered.handler.ts
  src/listeners/substrate-listener/commands/orders/order-refunded/order-refunded.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-created/service-request-created.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-partial/service-request-partial.handler.ts
  test/unit/endpoints/verification/verification.service.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-created/genetic-analysis-order-created.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-paid/genetic-analysis-order-paid.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analysis/genetic-analysis-rejected/genetic-analysis-rejected.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-created/service-request-created.handler.spec.ts
Labels: feature, test

#391 ci: update sleuth webhook
  .github/workflows/deploy.yml
Labels: ci

#397 fix: add country code in response
  src/endpoints/substrate-endpoint/interface/service-request.interface.ts
  src/endpoints/substrate-endpoint/services/service-request.service.ts
Labels: fix

#392 feat: endpoint Dna Collection Process category and testing
  src/app.module.ts
  src/endpoints/category/dna-collection/dna-collection.controller.ts
  src/endpoints/category/dna-collection/dna-collection.module.ts
  src/endpoints/category/dna-collection/dna-collection.service.ts
  src/endpoints/category/dna-collection/models/dna-collection.entity.ts
  src/endpoints/category/dna-collection/models/response.ts
  src/endpoints/email/email.module.ts
  test/e2e/endpoints/category/dna-collection.mock.data.ts
  test/e2e/endpoints/category/dna-collection.spec.ts
  test/e2e/fixture.ts
  test/unit/endpoints/category/dna-collection/dna-collection.controller.spec.ts
  test/unit/endpoints/category/dna-collection/dna-collection.service.spec.ts
Labels: feature, test

#393 feat: transaction hash update when fulfilled and refunded
  src/listeners/ethereum-listener/ethereum-listener.handler.ts
  src/listeners/ethereum-listener/ethereum-listener.module.ts
  test/unit/listeners/ethereum-listener/ethereum-listener.handler.spec.ts
Labels: feature, test

#394 fixing: refunded order smart contract not trigger
  src/common/modules/escrow/escrow.service.ts
  src/listeners/substrate-listener/commands/orders/order-failed/order-failed.handler.ts
  test/unit/common/modules/escrow/escrow.service.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-failed/order-failed.handler.spec.ts
Labels: fix, test

#396 feat: logging service charge
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-fulfilled/genetic-analysis-order-fulfilled.handler.ts
Labels: improvement

#398 refactor: Email e2e subject
  src/common/modules/mailer/mailer.manager.ts
Labels: improvement

#395 refactor: merge reward logging with transaction logging
  src/app.module.ts
  src/common/modules/escrow/escrow.service.ts
  src/common/modules/index.ts
  src/common/modules/reward/dto/reward.dto.ts
  src/common/modules/reward/index.ts
  src/common/modules/reward/models/reward.entity.ts
  src/common/modules/reward/reward.module.ts
  src/common/modules/reward/reward.service.ts
  src/common/modules/transaction-logging/dto/transaction-logging.dto.ts
  src/common/modules/transaction-logging/models/transaction-request.entity.ts
  src/common/modules/transaction-logging/transaction-logging.service.ts
  src/endpoints/email/email.module.ts
  src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
  src/endpoints/substrate-endpoint/substrate-endpoint.module.ts
  src/endpoints/verification/verification.module.ts
  src/endpoints/verification/verification.service.ts
  src/listeners/substrate-listener/commands/genetic-testing/data-staked/data-staked.handler.ts
  src/listeners/substrate-listener/commands/orders/order-failed/order-failed.handler.ts
  src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
  src/listeners/substrate-listener/substrate-listener.module.ts
  test/e2e/endpoints/email.spec.ts
  test/e2e/endpoints/substrate-endpoint.spec.ts
  test/e2e/endpoints/verification.spec.ts
  test/e2e/fixture.ts
  test/unit/common/modules/reward/reward.service.spec.ts
  test/unit/endpoints/substrate-endpoint/substrate-endpoint.controller.spec.ts
  test/unit/endpoints/verification/verification.service.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.spec.ts
  test/unit/mock.ts
Labels: improvement, test

#400 tests: order fulfilled listener integration testing
  package-lock.json
  package.json
  test/e2e/elasticsearch-listener-fixture.ts
  test/e2e/jest-e2e-endpoint.json
  test/e2e/jest-e2e-listener.json
  test/e2e/jest-e2e-scheduler.json
  test/e2e/listeners/substrate-listener/commands/orders/order-fulfilled.spec.ts
  test/e2e/polkadot-init.ts
  test/e2e/setup-listener.ts
  test/e2e/substrate-listener-fixture.ts
Labels: ci, test

#402 ci: improve sleuth webhook
  .github/workflows/deploy.yml
Labels: ci
