Repository debionetwork/debio-backend, pull requests merged in 2022-08, with the labels that each got.

#430 feat: remove reward from wallet binding
  src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
  test/unit/endpoints/substrate-endpoint/substrate-endpoint.controller.spec.ts
Labels: improvement, test

#434 update field name country service request
  src/endpoints/substrate-endpoint/interface/service-request.interface.ts
  src/endpoints/substrate-endpoint/services/service-request.service.ts
Labels: improvement

#432 improvement: enhance notification model
  src/common/modules/notification/models/notification.entity.ts
  src/common/modules/notification/notification.service.ts
  src/endpoints/notification-endpoint/notification-endpoint.controller.ts
  test/e2e/endpoints/notification-endpoint.spec.ts
  test/e2e/fixture.ts
  test/unit/common/modules/notification/notification.service.spec.ts
Labels: improvement

#435 fix: error parse transaction type
  package-lock.json
  package.json
  src/common/modules/transaction-type/models/transaction-type.entity.ts
Labels: fix

#436 fix: update response structure substrate countries
  src/endpoints/substrate-endpoint/interface/service-request.interface.ts
  src/endpoints/substrate-endpoint/services/service-request.service.ts
Labels: fix

#438 feat: read notification by ids
  src/common/modules/notification/notification.service.ts
  src/endpoints/notification-endpoint/dto/data-list-id.dto.ts
  src/endpoints/notification-endpoint/notification-endpoint.controller.ts
  src/endpoints/substrate-endpoint/services/lab.service.ts
  test/e2e/endpoints/notification-endpoint.spec.ts
  test/e2e/fixture.ts
  test/unit/endpoints/substrate-endpoint/services/lab.service.spec.ts
Labels: feature

#437 refactor: google cloud secret manager
  package-lock.json
  package.json
  src/app.module.ts
  src/common/modules/caches/index.ts
  src/common/modules/debio-conversion/debio-conversion.service.ts
  src/common/modules/escrow/escrow.service.ts
  src/common/modules/ethereum/ethereum.service.ts
  src/common/modules/health-indicators/elasticsearch.health/index.ts
  src/common/modules/mailer/mailer.manager.ts
  src/common/modules/mailer/mailer.module.ts
  src/common/modules/substrate/substrate.service.ts
  src/common/secrets/index.ts
  src/endpoints/authentication/authentication.controller.ts
  src/endpoints/authentication/pinata-jwt.model.ts
  src/endpoints/bounty/bounty.module.ts
  src/endpoints/cloud-storage/cloud-storage.module.ts
  src/endpoints/email/email.controller.ts
  src/endpoints/recaptcha/recaptcha.controller.ts
  src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
  src/endpoints/substrate-endpoint/substrate-endpoint.module.ts
  src/endpoints/transaction/transaction.module.ts
  src/endpoints/verification/verification.controller.ts
  test/e2e/endpoints/authentication.spec.ts
  test/e2e/endpoints/bounty.spec.ts
  test/e2e/endpoints/cloud-storage.spec.ts
  test/e2e/endpoints/email.spec.ts
  test/e2e/endpoints/health.spec.ts
  test/e2e/endpoints/substrate-endpoint.spec.ts
  test/e2e/endpoints/transaction.spec.ts
  test/e2e/endpoints/verification.spec.ts
  test/unit/endpoints/authentication/authentication.controller.spec.ts
  test/unit/mock.ts
Labels: improvement
