Repository debionetwork/debio-backend, pull requests merged in 2022-07, with the labels that each got.

#405 fix: logging stake, unstaked and notification request analyst submitted
  package-lock.json
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysys-order-created/genetic-analysis-order-created.handler.ts
  src/listeners/substrate-listener/commands/labs/stake-successfull/stake-successful.handler.ts
  src/listeners/substrate-listener/commands/labs/unstake-successfull/unstaked-successful.handler.ts
  test/e2e/listener-test-sequencer.js
  test/e2e/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-created.spec.ts
  test/e2e/listeners/substrate-listener/commands/labs/stake-successful.spec.ts
  test/e2e/listeners/substrate-listener/commands/labs/unstake-successful.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-created/genetic-analysis-order-created.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/lab/lab-staked-successful/lab-staked-successful.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/lab/lab-unstaked-successful/lab-unstaked-successful.handler.spec.ts
Labels: fix, test

#406 feat: notification ga verification status change
  src/listeners/substrate-listener/commands/genetic-analysts/genetic-analyst-verification-status/genetic-analyst-verification-status.handler.ts
  test/e2e/listeners/substrate-listener/commands/genetic-analysts/genetic-analyst-verification-status.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analyst/genetic-analyst-verification-status/genetic-analyst-verification-status.handler.spec.ts
  test/unit/mock.ts
Labels: feature, test

#408 fix: notification genetic analysis new order paid to seller
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-paid/genetic-analysis-order-paid.handler.ts
  test/e2e/listener-test-sequencer.js
  test/e2e/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-paid.spec.ts
Labels: fix, improvement, test

#410 fix: endpoint substrate/countries 500
  src/endpoints/substrate-endpoint/services/service-request.service.ts
Labels: fix

#412 ci: update version & formatting
  .github/workflows/builder.yml
  .github/workflows/create-tags.yml
  .github/workflows/deploy.yml
  .github/workflows/release.yml
  .github/workflows/tester.yml
  .github/workflows/update-version.yml
Labels: ci

#414 ci: fix create tags & release
  .github/workflows/create-tags.yml
  .github/workflows/deploy.yml
  .github/workflows/release.yml
Labels: ci

#413 fix: google secret manager
  package-lock.json
  package.json
  src/app.module.ts
  src/common/modules/caches/index.ts
  src/common/modules/debio-conversion/debio-conversion.module.ts
  src/common/modules/debio-conversion/debio-conversion.service.ts
  src/common/modules/escrow/escrow.module.ts
  src/common/modules/ethereum/ethereum.service.ts
  src/common/modules/health-indicators/elasticsearch.health/index.ts
  src/common/modules/mailer/mailer.manager.ts
  src/common/modules/mailer/mailer.module.ts
  src/common/modules/substrate/index.ts
  src/common/modules/substrate/substrate.service.ts
  src/endpoints/authentication/authentication.controller.ts
  src/endpoints/authentication/authentication.module.ts
  src/endpoints/bounty/bounty.module.ts
  src/endpoints/category/emr/emr.module.ts
  src/endpoints/cloud-storage/cloud-storage.module.ts
  src/endpoints/email/email.controller.ts
  src/endpoints/email/email.module.ts
  src/endpoints/rating/rating.module.ts
  src/endpoints/recaptcha/recaptcha.module.ts
  src/endpoints/substrate-endpoint/substrate-endpoint.module.ts
  src/endpoints/transaction/transaction.module.ts
  src/endpoints/verification/verification.controller.ts
  src/endpoints/verification/verification.module.ts
  src/main.ts
  test/e2e/endpoints/authentication.spec.ts
  test/e2e/endpoints/bounty.spec.ts
  test/e2e/endpoints/cloud-storage.spec.ts
  test/e2e/endpoints/email.spec.ts
  test/e2e/endpoints/health.spec.ts
  test/e2e/endpoints/substrate-endpoint.spec.ts
  test/e2e/endpoints/transaction.spec.ts
  test/e2e/endpoints/verification.spec.ts
  test/unit/common/modules/debio-conversion/debio-conversion.service.spec.ts
  test/unit/common/modules/ethereum/ethereum.service.spec.ts
  test/unit/common/modules/mailer/mailer.manager.spec.ts
  test/unit/common/modules/substrate/substrate.service.spec.ts
Labels: fix

#415 ci: revert "fix create tags & release"
  .github/workflows/create-tags.yml
  .github/workflows/deploy.yml
  .github/workflows/release.yml
Labels: ci

#416 ci: revert "update version & formatting"
  .github/workflows/builder.yml
  .github/workflows/create-tags.yml
  .github/workflows/deploy.yml
  .github/workflows/release.yml
  .github/workflows/tester.yml
  .github/workflows/update-version.yml
Labels: ci

#417 ci: revert "improve github workflows"
  .github/workflows/builder.yml
  .github/workflows/create-tags.yml
  .github/workflows/deploy.yml
  .github/workflows/release.yml
Labels: ci

#418 ci: added new env google project id
  .github/workflows/deploy.yml
Labels: ci

#419 ci: fixed project permission
  .github/workflows/deploy.yml
Labels: ci

#420 ci: added gca
  .github/workflows/deploy.yml
Labels: ci

#421 ci: fix helm upgrade
  .github/workflows/deploy.yml
Labels: ci

#423 chore: bump version to 2.2.3
  package-lock.json
  package.json
Labels: feature

#425 refactor: transaction logging
  src/common/modules/caches/caches.service.ts
  src/common/modules/caches/interface/transaction-status.interface.ts
  src/common/modules/caches/interface/transaction-type.interface.ts
  src/common/modules/transaction-logging/dto/transaction-logging.dto.ts
  src/common/modules/transaction-logging/transaction-logging.module.ts
  src/common/modules/transaction-logging/transaction-logging.service.ts
  src/common/modules/transaction-status/models/transaction-status.entity.ts
  src/common/modules/transaction-status/models/transaction-status.list.ts
  src/common/modules/transaction-status/transaction-status.module.ts
  src/common/modules/transaction-status/transaction-status.service.ts
  src/common/modules/transaction-type/models/transaction-type.entity.ts
  src/common/modules/transaction-type/models/transaction-type.list.ts
  src/common/modules/transaction-type/transaction-type.module.ts
  src/common/modules/transaction-type/transaction-type.service.ts
  src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
  src/endpoints/verification/verification.service.ts
  test/e2e/fixture.ts
  test/unit/common/modules/transaction-logging/transaction-logging.service.spec.ts
  test/unit/common/modules/transaction-status/transaction-status.service.spec.ts
  test/unit/common/modules/transaction-type/transaction-type.service.spec.ts
  test/unit/endpoints/verification/verification.service.spec.ts
Labels: improvement, test
