Repository debionetwork/debio-backend, pull requests merged in 2022-02, with the labels that each got.

#258 Improve tester
  .github/workflows/rcb_config.json
  .github/workflows/tester.yml
Labels: CI

#257 [DBIO-1680 & DBIO-1681] Specialization api category
  src/app.module.ts
  src/endpoints/category/service/service-category.controller.ts
  src/endpoints/category/service/service-category.service.ts
  src/endpoints/category/specialization/models/specialization.entity.ts
  src/endpoints/category/specialization/specialization.controller.ts
  src/endpoints/category/specialization/specialization.module.ts
  src/endpoints/category/specialization/specialization.service.ts
  test/unit/endpoints/category/specialization/specialization.controller.spec.ts
  test/unit/endpoints/category/specialization/specialization.service.spec.ts
Labels: enhancement, tests

#256 [DBIO-1594 & DBIO-1601] unit testing scheduler and endpoint Mailer
  package-lock.json
  package.json
  src/schedulers/mailer/mailer.service.spec.ts
  src/schedulers/mailer/mailer.service.ts
  test/unit/endpoints/email/email.controller.spec.ts
  test/unit/mock.ts
  test/unit/schedulers/mailer/mailer.service.spec.ts
Labels: tests

#260 [DBIO-1781] ci: add nodeSelector to deployment
  .github/workflows/deploy.yml
  .github/workflows/tester.yml
  README.md
Labels: CI

#261 [DBIO-1781] ci: add nodeSelector to deployment
  .github/workflows/deploy.yml
Labels: duplicate

#262 [DBIO-1724 & DBIO-1726] api genetic analys tracking
  src/endpoints/substrate-endpoint/services/genetic-analysis.ts
  src/endpoints/substrate-endpoint/services/index.ts
  src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
  src/endpoints/substrate-endpoint/substrate-endpoint.module.ts
  test/unit/endpoints/substrate-endpoint/services/genetic-analysis.service.spec.ts
  test/unit/endpoints/substrate-endpoint/substrate-endpoint.controller.spec.ts
Labels: enhancement, tests

#263 [DBIO-1699 & DBIO-1700]genetic analysis verification
  src/common/polkadot-provider/command/genetic-analyst.ts
  src/common/polkadot-provider/command/index.ts
  src/common/polkadot-provider/models/genetic-analysts/genetic-analyst-info.ts
  src/common/polkadot-provider/models/genetic-analysts/genetic-analyst-verification-status.ts
  src/common/polkadot-provider/models/genetic-analysts/index.ts
  src/endpoints/substrate-endpoint/services/genetic-analysis.ts
  src/endpoints/verification/verification.controller.ts
  src/endpoints/verification/verification.service.ts
  test/unit/endpoints/verification/verification.controller.spec.ts
  test/unit/endpoints/verification/verification.service.spec.ts
Labels: enhancement, tests

#266 [DBIO-1826 & DBIO-1827]Genetic analysis order
  src/common/polkadot-provider/command/genetic-analysis-order.ts
  src/common/polkadot-provider/command/index.ts
  src/common/polkadot-provider/index.ts
  src/common/polkadot-provider/models/genetic-analysis-orders/genetic-analysis-order-status.ts
  src/common/polkadot-provider/models/genetic-analysis-orders/index.ts
  src/common/polkadot-provider/models/index.ts
  src/common/polkadot-provider/models/orders/index.ts
  src/common/polkadot-provider/models/service-request/index.ts
  src/endpoints/substrate-endpoint/services/genetic-analysis-order.service.ts
  src/endpoints/substrate-endpoint/services/genetic-analysis.service.ts
  src/endpoints/substrate-endpoint/services/index.ts
  src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
  src/endpoints/substrate-endpoint/substrate-endpoint.module.ts
  src/listeners/substrate-listener/commands/helper/converter.ts
  src/listeners/substrate-listener/commands/orders/order-cancelled/order-cancelled.handler.ts
  src/listeners/substrate-listener/commands/orders/order-created/order-created.handler.ts
  src/listeners/substrate-listener/commands/orders/order-failed/order-failed.handler.ts
  src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
  src/listeners/substrate-listener/commands/orders/order-paid/order-paid.handler.ts
  src/listeners/substrate-listener/commands/orders/order-refunded/order-refunded.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-created/service-request-created.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-unstaked/service-request-unstaked.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-waiting-for-unstaked/service-request-waiting-for-unstaked.handler.ts
  test/unit/endpoints/substrate-endpoint/services/genetic-analysis-order-service.spec.ts
  test/unit/endpoints/substrate-endpoint/services/genetic-analysis.service.spec.ts
  test/unit/endpoints/substrate-endpoint/substrate-endpoint.controller.spec.ts
Labels: enhancement, tests

#267 [DBIO-1728] Genetic Analisys Order listener
  src/common/polkadot-provider/models/genetic-analysis-orders/index.ts
  src/endpoints/substrate-endpoint/dto/genetic-analysis-order-paid.dto.ts
  src/endpoints/substrate-endpoint/dto/index.ts
  src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-paid/genetic-analysis-order-paid.command.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-paid/genetic-analysis-order-paid.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysys-order-created/genetic-analysis-order-created.command.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysys-order-created/genetic-analysis-order-created.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/index.ts
  src/listeners/substrate-listener/substrate-listener.handler.ts
  src/listeners/substrate-listener/substrate-listener.module.ts
  test/unit/endpoints/substrate-endpoint/substrate-endpoint.controller.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-created/genetic-analysis-order-created.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-created/genetic-anaysis-order-created.command.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-paid/genetic-analysis-order-paid.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-paid/genetic-anaysis-order-paid.command.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-cancelled/order-cancelled.command.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-created/order-created.command.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-failed/order-failed.command.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.command.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-paid/order-paid.command.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-refunded/order-refunded.command.spec.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-created/service-request-created.command.spec.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-created/service-request-created.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-processed/service-request-processed.command.spec.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-unstaked/service-request-unstaked.command.spec.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-wating-for-unstaked/service-request-waiting-for-unstaked.command.spec.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-wating-for-unstaked/service-request-wating-for-unstaked.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/services/service-created/service-created.command.spec.ts
  test/unit/listeners/substrate-listener/commands/services/service-created/service-created.handler.spec.ts
  test/unit/mock.ts
  test/unit/schedulers/mailer/mailer.service.spec.ts
Labels: enhancement, tests

#268 [DBIO-1835 & DBIO-1837] feat : Genetic Analysis Order Listener : Rejected, Refunded, ResultReady, and Fulfilled
  src/common/polkadot-provider/command/genetic-analysis-order.ts
  src/common/polkadot-provider/models/genetic-analysis/genetic-analysis-status.ts
  src/common/polkadot-provider/models/genetic-analysis/index.ts
  src/common/polkadot-provider/models/index.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-fulfilled/genetic-analysis-order-fulfilled.command.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-fulfilled/genetic-analysis-order-fulfilled.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-refunded/genetic-analysis-order-refunded.command.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-refunded/genetic-analysis-order-refunded.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/index.ts
  src/listeners/substrate-listener/commands/genetic-analysis/genetic-analysis-rejected/genetic-analysis-rejected.command.ts
  src/listeners/substrate-listener/commands/genetic-analysis/genetic-analysis-rejected/genetic-analysis-rejected.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis/genetic-analysis-resultready/genetic-analysis-result-ready.command.ts
  src/listeners/substrate-listener/commands/genetic-analysis/genetic-analysis-resultready/genetic-analysis-result-ready.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis/index.ts
  src/listeners/substrate-listener/substrate-listener.handler.ts
  src/listeners/substrate-listener/substrate-listener.module.ts
  test/unit/endpoints/substrate-endpoint/services/genetic-analysis-order-service.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-fulfilled/genetic-analysis-order-fulfilled.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-fulfilled/genetic-anaysis-order-fulfilled.command.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-refunded/genetic-analysis-order-refunded.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-refunded/genetic-anaysis-order-refunded.command.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analysis/genetic-analysis-rejected/genetic-analysis-rejected.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analysis/genetic-analysis-rejected/genetic-anaysis-rejected.command.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analysis/geneticn-analysis-result-ready/genetic-analysis-result-ready.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analysis/geneticn-analysis-result-ready/genetic-anaysis-result-ready.command.spec.ts
  test/unit/mock.ts
Labels: enhancement, tests

#274 fix : resolve intermittent error on API
  test/unit/endpoints/substrate-endpoint/substrate-endpoint.controller.spec.ts
Labels: bug

#275 [DBIO-1869 & DBIO-1870] Stake and reject
  src/common/polkadot-provider/models/genetic-analysts/index.ts
  src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
  src/listeners/substrate-listener/commands/genetic-analysts/genetic-analyst-staked/genetic-analyst-staked.command.ts
  src/listeners/substrate-listener/commands/genetic-analysts/genetic-analyst-staked/genetic-analyst-staked.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysts/genetic-analyst-verification-status/genetic-analyst-verification-status.command.ts
  src/listeners/substrate-listener/commands/genetic-analysts/genetic-analyst-verification-status/genetic-analyst-verification-status.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysts/index.ts
  src/listeners/substrate-listener/substrate-listener.handler.ts
  src/listeners/substrate-listener/substrate-listener.module.ts
  test/unit/listeners/substrate-listener/commands/genetic-analyst/genetic-analyst-staked/genetic-analyst-staked.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analyst/genetic-analyst-staked/genetic-anayst-staked.command.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analyst/genetic-analyst-verification-status/genetic-analyst-verification-status.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analyst/genetic-analyst-verification-status/genetic-anayst-verification-status.command.spec.ts
  test/unit/mock.ts
Labels: enhancement, tests

#276 fix : minor typo and logger
  package.json
  src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
Labels: bug

#277 ci: increase request and limit resource of deployment
  .github/workflows/deploy.yml
Labels: CI

#279 [DBIO-1898] ci: add new env
  .github/workflows/deploy.yml
Labels: ci

#280 add AGPL-3.0 licence
  LICENSE
  README.md
Labels: document
