Repository debionetwork/debio-backend, pull requests merged in 2022-05, with the labels that each got.

#342 feat: Enhance listener and Error WASM
  src/app.module.ts
  src/listeners/substrate-listener/blocks/commands/set-last-substrate-block/set-last-substrate-block.command.ts
  src/listeners/substrate-listener/blocks/commands/set-last-substrate-block/set-last-substrate-block.handler.ts
  src/listeners/substrate-listener/blocks/index.ts
  src/listeners/substrate-listener/blocks/queries/get-last-substrate-block/get-last-substrate-block.handler.ts
  src/listeners/substrate-listener/blocks/queries/get-last-substrate-block/get-last-substrate-block.query.ts
  src/listeners/substrate-listener/substrate-listener.handler.ts
  src/listeners/substrate-listener/substrate-listener.module.ts
  src/main.ts
  test/unit/listeners/substrate-listener/substrate-listener.handler.spec.ts
Labels: fix, feature, test

#344 feat: listener, unit test for lab & fixing forward payment to escrow when order fulfilled
  src/listeners/substrate-listener/commands/labs/index.ts
  src/listeners/substrate-listener/commands/labs/registered/lab-registered.command.ts
  src/listeners/substrate-listener/commands/labs/registered/lab-registered.handler.ts
  src/listeners/substrate-listener/commands/labs/retrieve-unstake-amount/retrieve-unstake-amount.command.ts
  src/listeners/substrate-listener/commands/labs/retrieve-unstake-amount/retrieve-unstake-amount.handler.ts
  src/listeners/substrate-listener/commands/labs/stake-successfull/stake-successful.command.ts
  src/listeners/substrate-listener/commands/labs/stake-successfull/stake-successful.handler.ts
  src/listeners/substrate-listener/commands/labs/unstake-successfull/unstaked-successful.command.ts
  src/listeners/substrate-listener/commands/labs/unstake-successfull/unstaked-successful.handler.ts
  src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-created/service-request-created.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-unstaked/service-request-unstaked.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-waiting-for-unstaked/service-request-waiting-for-unstaked.handler.ts
  src/listeners/substrate-listener/substrate-listener.handler.ts
  src/listeners/substrate-listener/substrate-listener.module.ts
  test/unit/listeners/substrate-listener/commands/lab/lab-registered/lab-registered.command.spec.ts
  test/unit/listeners/substrate-listener/commands/lab/lab-registered/lab-registered.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/lab/lab-retrieve-unstaked-amount/lab-retrieve-unstaked-amount.command.spec.ts
  test/unit/listeners/substrate-listener/commands/lab/lab-retrieve-unstaked-amount/lab-retrieve-unstaked-amount.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/lab/lab-staked-successful/lab-stake-successful.command.spec.ts
  test/unit/listeners/substrate-listener/commands/lab/lab-staked-successful/lab-staked-successful.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/lab/lab-unstaked-successful/lab-unstaked-successful.command.spec.ts
  test/unit/listeners/substrate-listener/commands/lab/lab-unstaked-successful/lab-unstaked-successful.handler.spec.ts
  test/unit/mock.ts
Labels: fix, feature, test

#349 feat: add field to substrate/labs and unit test
  src/endpoints/substrate-endpoint/services/lab.service.ts
  test/unit/endpoints/substrate-endpoint/services/lab.service.spec.ts
Labels: feature, test

#350 ci: improve deployment resource request
  .github/workflows/deploy.yml
Labels: ci

#356 fix : Fix reconnect to polkadot
  src/common/modules/substrate/substrate.service.ts
  test/unit/common/modules/substrate/substrate.service.spec.ts
Labels: fix

#359 ci: use self-hosted github action runner
  .github/workflows/build-failure.yml
  .github/workflows/builder.yml
Labels: ci

#360 ci: fix github workflows
  .github/workflows/build-failure.yml
  .github/workflows/builder.yml
Labels: ci

#361 ci: fix wlif permissions
  .github/workflows/build-failure.yml
  .github/workflows/builder.yml
Labels: ci

#363 fix: Fix double event
  src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
  src/listeners/substrate-listener/substrate-listener.handler.ts
  test/unit/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.spec.ts
Labels: fix

#365 CI: Docker Build Improvement
  .github/workflows/build-failure.yml
  .github/workflows/builder.yml
  .github/workflows/deploy.yml
  .maintain/docker/Dockerfile
Labels: ci

#366 fix: Fix double event
  src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
  src/listeners/substrate-listener/substrate-listener.handler.ts
  test/unit/listeners/substrate-listener/substrate-listener.handler.spec.ts
Labels: fix
