Repository debionetwork/debio-backend, pull requests merged in 2022-01, with the labels that each got.

#196 feat: new healthchecks.
  file/lastblock.txt
  src/common/health-indicators/elasticsearch.health/elasticsearch.health.indicator.ts
  src/common/health-indicators/elasticsearch.health/index.ts
  src/common/health-indicators/index.ts
  src/common/health-indicators/substrate.health/index.ts
  src/common/health-indicators/substrate.health/substrate.health.indicator.ts
  src/common/index.ts
  src/common/substrate/index.ts
  src/common/substrate/substrate.service.ts
  src/health/health.controller.ts
  src/health/health.module.ts
Labels: enhancement

#195 feat: sentry analytics.
  package-lock.json
  package.json
  src/bounty/bounty.controller.ts
  src/category/emr/emr.controller.ts
  src/category/service/service-category.controller.ts
  src/cloud-storage/cloud-storage.controller.ts
  src/common/index.ts
  src/common/interceptors/index.ts
  src/common/interceptors/sentry.interceptor.ts
  src/common/mailer/mailer.module.ts
  src/escrow/escrow.controller.ts
  src/ethereum-indexed-data/service-request/service-request.controller.ts
  src/ethereum/ethereum.controller.ts
  src/health/health.controller.ts
  src/location/location.controller.ts
  src/location/location.module.ts
  src/main.ts
  src/rating/rating.controller.ts
  src/recaptcha/recaptcha.controller.ts
  src/substrate-indexed-data/labs/lab.controller.ts
  src/substrate-indexed-data/orders/order.controller.ts
  src/substrate-indexed-data/services/service.controller.ts
  src/substrate/substrate.controller.ts
  src/verification/verification.controller.ts
Labels: enhancement

#200 [DBIO-1482] docs: readme.
  README.md
Labels: documentation

#197 Schedule unstaked
  src/schedulers/unstaked/unstaked.service.ts
  src/substrate/substrate.service.ts
Labels: bug, enhancement

#201 ci: improve github workflows
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/builder.yml
  .github/workflows/deploy.yml
  .github/workflows/main.yml
  .github/workflows/publish-draft-release-candidate.yml
  .github/workflows/publish-draft-release.yml
  .github/workflows/release.yml
Labels: CI

#202 ci: fix docker image repository
  .github/workflows/deploy.yml
Labels: CI

#204 [DBIO-1445] fix: service request.
  src/common/polkadot-provider/models/index.ts
  src/common/polkadot-provider/models/service-request/index.ts
  src/common/polkadot-provider/models/service-request/request-status.ts
  src/common/polkadot-provider/query/index.ts
  src/common/polkadot-provider/query/service-request.ts
  src/schedulers/unstaked/unstaked.service.ts
Labels: bug, refactor

#205 [DBIO-1446] refactor: substrate service and genetic testing event listeners.
  package-lock.json
  package.json
  src/app.module.ts
  src/common/polkadot-provider/command/genetic-testing.ts
  src/common/polkadot-provider/command/labs.ts
  src/common/polkadot-provider/command/orders.ts
  src/endpoints/substrate-endpoint/dto/get-dbio-on-register.dto.ts
  src/endpoints/substrate-endpoint/dto/index.ts
  src/endpoints/substrate-endpoint/dto/wallet-binding.dto.ts
  src/endpoints/substrate-endpoint/labs/lab.controller.ts
  src/endpoints/substrate-endpoint/orders/order.controller.ts
  src/endpoints/substrate-endpoint/services/index.ts
  src/endpoints/substrate-endpoint/services/lab.service.ts
  src/endpoints/substrate-endpoint/services/order.service.ts
  src/endpoints/substrate-endpoint/services/service.controller.ts
  src/endpoints/substrate-endpoint/services/service.service.ts
  src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
  src/endpoints/substrate-endpoint/substrate-endpoint.module.ts
  src/endpoints/substrate-endpoint/substrate.controller.spec.ts
  src/listeners/substrate-listener/commands/genetic-testing/data-staked/data-staked.command.ts
  src/listeners/substrate-listener/commands/genetic-testing/data-staked/data-staked.event-model.ts
  src/listeners/substrate-listener/commands/genetic-testing/data-staked/data-staked.handler.ts
  src/listeners/substrate-listener/commands/genetic-testing/index.ts
  src/listeners/substrate-listener/commands/services/index.ts
  src/listeners/substrate-listener/commands/services/service-created/service-created.command.ts
  src/listeners/substrate-listener/commands/services/service-created/service-created.handler.ts
  src/listeners/substrate-listener/models/block-metadata.event-model.ts
  src/listeners/substrate-listener/substrate-listener.handler.ts
  src/listeners/substrate-listener/substrate-listener.module.ts
  test/unit/endpoints/substrate-indexed-data/labs/lab.controller.spec.ts
  test/unit/endpoints/substrate-indexed-data/labs/lab.service.spec.ts
  test/unit/endpoints/substrate-indexed-data/services/service.controller.spec.ts
  test/unit/endpoints/substrate-indexed-data/services/service.service.spec.ts
  test/unit/endpoints/verification/verification.service.spec.ts
Labels: refactor

#207 [DBIO-1504] refactor: substrate order listener.
  src/common/polkadot-provider/models/service-request/index.ts
  src/common/polkadot-provider/models/service-request/service-invoice.ts
  src/common/polkadot-provider/query/service-request.ts
  src/common/polkadot-provider/query/user-profile.ts
  src/listeners/substrate-listener/commands/orders/index.ts
  src/listeners/substrate-listener/commands/orders/order-cancelled/order-cancelled.command.ts
  src/listeners/substrate-listener/commands/orders/order-cancelled/order-cancelled.handler.ts
  src/listeners/substrate-listener/commands/orders/order-created/order-created.command.ts
  src/listeners/substrate-listener/commands/orders/order-created/order-created.handler.ts
  src/listeners/substrate-listener/commands/orders/order-failed/order-failed.command.ts
  src/listeners/substrate-listener/commands/orders/order-failed/order-failed.handler.ts
  src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.command.ts
  src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
  src/listeners/substrate-listener/commands/orders/order-paid/order-paid.command.ts
  src/listeners/substrate-listener/commands/orders/order-paid/order-paid.handler.ts
  src/listeners/substrate-listener/commands/orders/order-refunded/order-refunded.command.ts
  src/listeners/substrate-listener/commands/orders/order-refunded/order-refunded.handler.ts
  src/listeners/substrate-listener/substrate-listener.handler.ts
  src/listeners/substrate-listener/substrate-listener.module.ts
Labels: refactor

#208 [DBIO-1505] refactor: substrate service request listener.
  src/common/polkadot-provider/query/service-request.ts
  src/listeners/substrate-listener/commands/service-request/index.ts
  src/listeners/substrate-listener/commands/service-request/service-request-created/service-request-created.command.ts
  src/listeners/substrate-listener/commands/service-request/service-request-created/service-request-created.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-processed/service-request-processed.command.ts
  src/listeners/substrate-listener/commands/service-request/service-request-processed/service-request-processed.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-unstaked/service-request-unstaked.command.ts
  src/listeners/substrate-listener/commands/service-request/service-request-unstaked/service-request-unstaked.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-waiting-for-unstaked/service-request-waiting-for-unstaked.command.ts
  src/listeners/substrate-listener/commands/service-request/service-request-waiting-for-unstaked/service-request-waiting-for-unstaked.handler.ts
  src/listeners/substrate-listener/substrate-listener.handler.ts
  src/listeners/substrate-listener/substrate-listener.module.ts
Labels: refactor

#206 [DBIO-1179 & DBIO-1508] refactor: mailer module.
  file/lastblock.txt
  nest-cli.json
  package-lock.json
  src/app.module.ts
  src/common/modules/mailer/mailer.controller.ts
  src/common/modules/mailer/mailer.manager.ts
  src/common/modules/mailer/mailer.module.ts
  src/common/modules/mailer/models/lab-register.model/certification.ts
  src/common/modules/mailer/models/lab-register.model/index.ts
  src/common/modules/mailer/models/lab-register.model/service.ts
  src/endpoints/email/email.controller.ts
  src/endpoints/email/email.module.ts
  src/endpoints/escrow/escrow.controller.spec.ts
  src/endpoints/escrow/escrow.controller.ts
  src/endpoints/escrow/escrow.module.ts
  src/endpoints/escrow/escrow.service.ts
  src/endpoints/ethereum/ethereum.controller.ts
  src/endpoints/ethereum/ethereum.service.ts
  src/listeners/substrate-listener/commands/services/service-created/service-created.handler.ts
Labels: refactor

#211 [DBIO-1224] tests: reward service unit tests.
  test/unit/common/modules/mailer/mailer.manager.spec.ts
  test/unit/common/modules/mailer/mailer.mock.data.ts
  test/unit/common/modules/reward/reward.service.spec.ts
Labels: tests

#212 [DBIO-1220] tests: trans logging unit tests.
  test/unit/common/modules/transaction-logging/transaction-logging.service.spec.ts
Labels: tests

#213 [DBIO-1233] tests: debio conversion service unit tests.
  package-lock.json
  src/common/modules/debio-conversion/debio-conversion.module.ts
  src/common/modules/debio-conversion/debio-conversion.service.ts
  test/unit/common/modules/debio-conversion/debio-conversion.service.spec.ts
Labels: refactor, tests

#215 [DBIO-1227] tests: city service unit tests.
  test/unit/endpoints/location/city.service.spec.ts
  test/unit/mock.ts
Labels: tests

#216 [DBIO-1229] tests: location controller unit tests.
  src/endpoints/location/location.controller.spec.ts
  test/unit/endpoints/location/location.controller.spec.ts
Labels: tests

#214 [DBIO-1339] transaction endpoint for save transaction hash
  src/common/modules/transaction-logging/models/transaction-request.entity.ts
  src/common/modules/transaction-logging/transaction-logging.service.ts
  src/endpoints/transaction/dto/transaction-hash.dto.ts
  src/endpoints/transaction/transaction.controller.ts
  src/endpoints/transaction/transaction.module.ts
  src/endpoints/transaction/transaction.service.ts
  test/unit/common/modules/transaction-logging/transaction-logging.service.spec.ts
  test/unit/mock.ts
Labels: enhancement, tests

#217 [DBIO-1479 & DBIO-1371] fix: mainnet backend error.
  file/lastblock.txt
  src/common/modules/debio-conversion/debio-conversion.service.ts
  src/common/polkadot-provider/query/account.ts
  src/endpoints/ethereum-indexed-data/service-request/service-request.service.ts
  src/endpoints/location/country.service.ts
  src/endpoints/location/state.service.ts
  src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
  src/listeners/substrate-listener/substrate-listener.handler.ts
Labels: bug

#219 [DBIO-1486] refactor: save last eth/substrate block using Redis.
  package-lock.json
  package.json
  src/app.module.ts
  src/common/modules/caches/caches.service.ts
  src/common/modules/caches/index.ts
  src/common/modules/index.ts
  src/endpoints/ethereum/ethereum.controller.ts
  src/endpoints/ethereum/ethereum.module.ts
  src/endpoints/ethereum/ethereum.service.ts
  test/unit/common/modules/cache/caches.service.spec.ts
Labels: refactor, tests

#220 [DBIO-1225] tests: rating module unit tests.
  package-lock.json
  package.json
  src/common/modules/debio-conversion/debio-conversion.module.ts
  src/common/modules/mailer/mailer.manager.ts
  src/common/proxies/date-time/date-time.proxy.ts
  src/endpoints/rating/rating.controller.spec.ts
  src/endpoints/rating/rating.controller.ts
  src/endpoints/rating/rating.service.ts
  test/unit/common/modules/cache/caches.service.spec.ts
  test/unit/common/modules/debio-conversion/debio-conversion.service.spec.ts
  test/unit/common/modules/mailer/mailer.manager.spec.ts
  test/unit/endpoints/rating/rating.controller.spec.ts
  test/unit/endpoints/rating/rating.service.spec.ts
  test/unit/mock.ts
Labels: bug, refactor, tests

#221 fix: rating module.
  file/lastblock.txt
  src/app.module.ts
  src/common/modules/caches/caches.service.ts
  src/common/modules/caches/index.ts
  src/common/modules/debio-conversion/debio-conversion.module.ts
  src/common/modules/debio-conversion/debio-conversion.service.ts
  src/common/modules/mailer/mailer.manager.ts
  src/common/modules/mailer/mailer.module.ts
  src/common/modules/mailer/models/lab-register.model/service.ts
  src/common/modules/transaction-logging/models/transaction-request.entity.ts
  src/common/modules/transaction-logging/transaction-logging.service.ts
  src/endpoints/ethereum-indexed-data/service-request/service-request.service.ts
  src/endpoints/ethereum/ethereum.module.ts
  src/endpoints/ethereum/ethereum.service.ts
  src/endpoints/location/country.service.ts
  src/endpoints/location/state.service.ts
  src/endpoints/rating/rating.controller.ts
  src/endpoints/rating/rating.module.ts
  src/endpoints/transaction/dto/transaction-hash.dto.ts
  src/endpoints/transaction/transaction.controller.ts
  src/endpoints/transaction/transaction.module.ts
  src/endpoints/transaction/transaction.service.ts
  src/listeners/substrate-listener/substrate-listener.handler.ts
  test/unit/common/modules/cache/caches.service.spec.ts
  test/unit/common/modules/debio-conversion/debio-conversion.service.spec.ts
  test/unit/common/modules/mailer/mailer.manager.spec.ts
  test/unit/common/modules/reward/reward.service.spec.ts
  test/unit/common/modules/transaction-logging/transaction-logging.service.spec.ts
  test/unit/endpoints/location/city.service.spec.ts
  test/unit/endpoints/location/location.controller.spec.ts
  test/unit/endpoints/rating/rating.controller.spec.ts
  test/unit/endpoints/rating/rating.service.spec.ts
  test/unit/endpoints/transaction/transaction.controller.spec.ts
  test/unit/endpoints/transaction/transaction.service.spec.ts
  test/unit/mock.ts
Labels: bug

#222 add new env
  .github/workflows/deploy.yml
Labels: CI

#223 rename deploy command
  .github/workflows/deploy.yml
Labels: CI

#224 [DBIO-1445] fix: substrate listeners.
  src/app.module.ts
  src/listeners/substrate-listener/commands/genetic-testing/data-staked/data-staked.handler.ts
  src/listeners/substrate-listener/commands/orders/order-cancelled/order-cancelled.handler.ts
  src/listeners/substrate-listener/commands/orders/order-created/order-created.handler.ts
  src/listeners/substrate-listener/commands/orders/order-failed/order-failed.handler.ts
  src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
  src/listeners/substrate-listener/commands/orders/order-paid/order-paid.handler.ts
  src/listeners/substrate-listener/commands/orders/order-refunded/order-refunded.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-created/service-request-created.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-unstaked/service-request-unstaked.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-waiting-for-unstaked/service-request-waiting-for-unstaked.handler.ts
  src/listeners/substrate-listener/commands/services/service-created/service-created.handler.ts
  src/listeners/substrate-listener/substrate-listener.module.ts
  src/schedulers/unstaked/unstaked.service.ts
Labels: bug, refactor

#225 fix: uncommented scheduler.
  src/schedulers/unstaked/unstaked.service.ts
Labels: bug

#226 fix helm command typo
  .github/workflows/deploy.yml
Labels: CI

#228 [DBIO-1180] refactor: process env proxy for dependencies.
  src/common/index.ts
  src/common/modules/caches/index.ts
  src/common/modules/debio-conversion/debio-conversion.module.ts
  src/common/modules/debio-conversion/debio-conversion.service.ts
  src/common/modules/index.ts
  src/common/modules/proxies/date-time/date-time.module.ts
  src/common/modules/proxies/date-time/date-time.proxy.ts
  src/common/modules/proxies/date-time/index.ts
  src/common/modules/proxies/index.ts
  src/common/modules/proxies/process-env/index.ts
  src/common/modules/proxies/process-env/process-env.module.ts
  src/common/modules/proxies/process-env/process-env.proxy.ts
  src/common/modules/reward/reward.module.ts
  src/common/modules/substrate/index.ts
  src/common/modules/substrate/substrate.service.ts
  src/endpoints/bounty/bounty.controller.ts
  src/endpoints/bounty/bounty.module.ts
  src/endpoints/cloud-storage/cloud-storage.controller.ts
  src/endpoints/cloud-storage/cloud-storage.module.ts
  src/endpoints/email/email.controller.ts
  src/endpoints/email/email.module.ts
  src/endpoints/escrow/escrow.module.ts
  src/endpoints/escrow/escrow.service.ts
  src/endpoints/ethereum-indexed-data/ethereum-indexed-data.module.ts
  src/endpoints/ethereum/ethereum.module.ts
  src/endpoints/ethereum/ethereum.service.ts
  src/endpoints/recaptcha/recaptcha.controller.ts
  src/endpoints/recaptcha/recaptcha.module.ts
  src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
  src/endpoints/verification/verification.module.ts
  src/endpoints/verification/verification.service.ts
  src/listeners/substrate-listener/commands/genetic-testing/data-staked/data-staked.handler.ts
  src/listeners/substrate-listener/commands/orders/order-created/order-created.handler.ts
  src/listeners/substrate-listener/commands/orders/order-paid/order-paid.handler.ts
  src/listeners/substrate-listener/commands/orders/order-refunded/order-refunded.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-created/service-request-created.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-unstaked/service-request-unstaked.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-waiting-for-unstaked/service-request-waiting-for-unstaked.handler.ts
  src/listeners/substrate-listener/commands/services/service-created/service-created.handler.ts
  src/listeners/substrate-listener/substrate-listener.module.ts
  test/unit/common/modules/debio-conversion/debio-conversion.service.spec.ts
  test/unit/endpoints/bounty/bounty.controller.spec.ts
  test/unit/endpoints/cloud-storage/cloud-storage.controller.spec.ts
  test/unit/endpoints/verification/verification.controller.spec.ts
  test/unit/endpoints/verification/verification.service.spec.ts
  test/unit/mock.ts
Labels: refactor

#230 [DBIO-1600] refactor: remove unused controllers.
  src/endpoints/substrate-endpoint/labs/lab.controller.ts
  src/endpoints/substrate-endpoint/orders/order.controller.ts
  src/endpoints/substrate-endpoint/services/service.controller.ts
  src/endpoints/substrate-endpoint/substrate-endpoint.module.ts
Labels: refactor

#229 [DBIO-1593] refactor: remove storage helper.
  src/common/modules/helper/index.ts
  src/common/modules/helper/storage.helper.ts
  src/common/modules/index.ts
Labels: refactor

#232 [DBIO-1597 & DBIO-1604] refactor: ethereum listeners and module.
  src/app.module.ts
  src/common/modules/ethereum/ethereum.module.ts
  src/common/modules/ethereum/ethereum.service.ts
  src/common/modules/ethereum/index.ts
  src/common/modules/ethereum/utils/ABI.json
  src/common/modules/ethereum/utils/Escrow.json
  src/common/modules/ethereum/utils/ServiceRequest.json
  src/common/modules/index.ts
  src/endpoints/escrow/escrow.module.ts
  src/endpoints/escrow/escrow.service.ts
  src/endpoints/ethereum-indexed-data/ethereum-indexed-data.module.ts
  src/endpoints/ethereum-indexed-data/service-request/service-request.service.ts
  src/endpoints/ethereum/ethereum.controller.spec.ts
  src/endpoints/ethereum/ethereum.module.ts
  src/endpoints/ethereum/ethereum.service.spec.ts
  src/listeners/ethereum-listener/ethereum-listener.handler.ts
  src/listeners/ethereum-listener/ethereum-listener.module.ts
  test/unit/common/modules/caches/caches.service.spec.ts
  test/unit/listeners/ethereum-listener/ethereum-listener.handler.spec.ts
Labels: refactor, tests

#238 [DBIO-1591] tests: process env proxy unit tests.
  test/unit/common/modules/proxies/process-env.proxy.spec.ts
Labels: tests

#233 [DBIO-1595] Endpoints/Ethereum-Indexed-Data Rename to Substrate-Endpoint
  src/app.module.ts
  src/endpoints/ethereum-indexed-data/ethereum-indexed-data.module.ts
  src/endpoints/ethereum-indexed-data/service-request/service-request.controller.ts
  src/endpoints/substrate-endpoint/services/service-request.service.ts
  src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
  src/endpoints/substrate-endpoint/substrate-endpoint.module.ts
Labels: refactor

#237 [DBIO-1588 & DBIO-1591] refactor: health indicator modules.
  src/common/index.ts
  src/common/modules/health-indicators/elasticsearch.health/elasticsearch.health.indicator.ts
  src/common/modules/health-indicators/elasticsearch.health/index.ts
  src/common/modules/health-indicators/index.ts
  src/common/modules/health-indicators/substrate.health/index.ts
  src/common/modules/health-indicators/substrate.health/substrate.health.indicator.ts
  src/common/modules/index.ts
  src/endpoints/health/health.controller.ts
  test/unit/common/modules/health-indicators/elasticsearch.health.indicator.spec.ts
  test/unit/common/modules/health-indicators/substrate.health.indicator.spec.ts
  test/unit/mock.ts
Labels: refactor, tests

#235 [DBIO-1596 & DBIO-1611] tests: ethereum service unit tests.
  src/common/modules/ethereum/ethereum.service.ts
  test/unit/common/modules/ethereum/ethereum.service.spec.ts
  test/unit/mock.ts
Labels: refactor, tests

#234 [DBIO-1599] tests: substrate endpoint unit tests.
  src/endpoints/substrate-endpoint/services/index.ts
  src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
  src/endpoints/substrate-endpoint/substrate-endpoint.module.ts
  src/endpoints/substrate-endpoint/substrate.controller.spec.ts
  test/unit/endpoints/substrate-endpoint/services/lab.service.spec.ts
  test/unit/endpoints/substrate-endpoint/services/service.service.spec.ts
  test/unit/endpoints/substrate-endpoint/substrate-endpoint.controller.spec.ts
  test/unit/endpoints/substrate-indexed-data/labs/lab.controller.spec.ts
  test/unit/endpoints/substrate-indexed-data/services/service.controller.spec.ts
Labels: refactor, tests

#236 [DBIO-1232] tests: moved escrow tests to new folder.
  src/endpoints/escrow/escrow.service.spec.ts
  src/endpoints/escrow/escrow.service.ts
  test/unit/endpoints/escrow/escrow.service.spec.ts
  test/unit/mock.ts
Labels: refactor, tests

#239 [DBIO-1602] tests: Scheduler/Unstaked
  package-lock.json
  src/endpoints/transaction/transaction.service.ts
  src/schedulers/unstaked/unstaked.service.spec.ts
  src/schedulers/unstaked/unstaked.service.ts
  test/unit/endpoints/transaction/transaction.controller.spec.ts
  test/unit/mock.ts
  test/unit/schedulers/unstaked/unstaked.service.spec.ts
Labels: tests

#241 [DBIO-1572] ci: implement unit tests on CI.
  .github/workflows/pull-request.yml
Labels: CI, tests

#244 [DBIO-1592 & DBIO-1620] tests: substrate service unit tests.
  src/common/modules/ethereum/index.ts
  src/common/modules/health-indicators/elasticsearch.health/elasticsearch.health.indicator.ts
  src/common/modules/health-indicators/substrate.health/substrate.health.indicator.ts
  src/endpoints/escrow/escrow.service.ts
  src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
  src/endpoints/substrate-endpoint/substrate-endpoint.module.ts
  src/listeners/ethereum-listener/ethereum-listener.module.ts
  test/unit/@polkadot-api.mock.ts.ts
  test/unit/common/modules/ethereum/ethereum.service.spec.ts
  test/unit/common/modules/health-indicators/elasticsearch.health.indicator.spec.ts
  test/unit/common/modules/health-indicators/substrate.health.indicator.spec.ts
  test/unit/common/modules/proxies/process-env.proxy.spec.ts
  test/unit/common/modules/substrate/substrate.service.spec.ts
  test/unit/endpoints/escrow/escrow.service.spec.ts
  test/unit/endpoints/substrate-endpoint/substrate-endpoint.controller.spec.ts
  test/unit/jest-unit.json
  test/unit/listeners/ethereum-listener/ethereum-listener.handler.spec.ts
  test/unit/mock.ts
  test/unit/schedulers/unstaked/unstaked.service.spec.ts
Labels: tests

#240 [DBIO-1619 & DBIO-1628] tests: recaptcha controller unit tests.
  src/endpoints/health/health.controller.spec.ts
  src/endpoints/recaptcha/recaptcha.controller.spec.ts
  src/endpoints/recaptcha/recaptcha.controller.ts
  test/unit/endpoints/health/health.controller.spec.ts
  test/unit/endpoints/recaptcha/recaptcha.controller.spec.ts
  test/unit/mock.ts
Labels: refactor, tests

#245 [DBIO-1603] tests: substrate listener handler unit tests.
  src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
  test/unit/@polkadot-types-interfaces.mock.ts
  test/unit/jest-unit.json
  test/unit/listeners/substrate-listener/substrate-listener.handler.spec.ts
  test/unit/listeners/substrate-listener/substrate-listener.mock.data.ts
Labels: refactor, tests

#246 [DBIO-1590 & DBIO-1605] order service and date proxy unit testing
  package-lock.json
  test/unit/common/modules/proxies/date-time.proxy.spec.ts
  test/unit/endpoints/substrate-endpoint/services/order.service.spec.ts
Labels: tests

#247 [DBIO-1590] date proxy unit testing
  src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
  test/unit/common/modules/proxies/date-time.proxy.spec.ts
Labels: tests

#243 [DBIO-1602] tests: Scheduler/Unstaked
  test/unit/mock.ts
  test/unit/schedulers/unstaked/unstaked.service.spec.ts
Labels: tests

#249 [DBIO-1606] tests: Endpoints/SubstrateEndpoints/ServiceRequest
  test/unit/endpoints/substrate-endpoint/services/service-request.service.spec.ts
  test/unit/mock.ts
Labels: tests

#248 [DBIO-1609] tests: Listener/OrdersEvent
  src/listeners/substrate-listener/commands/orders/order-created/order-created.handler.ts
  src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
  test/unit/listeners/substrate-listener/commands/orders/order-cancelled/order-cancelled.command.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-cancelled/order-cancelled.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-created/order-created.command.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-created/order-created.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-failed/order-failed.command.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-failed/order-failed.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.command.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-paid/order-paid.command.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-paid/order-paid.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-refunded/order-refunded.command.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-refunded/order-refunded.handler.spec.ts
  test/unit/mock.ts
Labels: tests

#250 [DBIO-1536] tests: Unit Test Service Request Events
  src/listeners/substrate-listener/commands/service-request/service-request-unstaked/service-request-unstaked.handler.ts
  src/listeners/substrate-listener/commands/service-request/service-request-waiting-for-unstaked/service-request-waiting-for-unstaked.handler.ts
  src/listeners/substrate-listener/substrate-listener.module.ts
  test/unit/@polkadot-types-interfaces.mock.ts
  test/unit/common/modules/proxies/date-time.proxy.spec.ts
  test/unit/endpoints/substrate-endpoint/services/order.service.spec.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-created/service-request-created.command.spec.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-created/service-request-created.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-processed/service-request-processed.command.spec.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-processed/service-request-processed.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-unstaked/service-request-unstaked.command.spec.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-unstaked/service-request-unstaked.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-wating-for-unstaked/service-request-waiting-for-unstaked.command.spec.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-wating-for-unstaked/service-request-wating-for-unstaked.handler.spec.ts
  test/unit/listeners/substrate-listener/substrate-listener.handler.spec.ts
  test/unit/listeners/substrate-listener/substrate-listener.mock.data.ts
  test/unit/mock.ts
  test/unit/schedulers/unstaked/unstaked.service.spec.ts
Labels: refactor, tests

#251 [DBIO-1630] [Refactor] Escrow Service to Common/Modules
  src/app.module.ts
  src/common/modules/escrow/escrow.module.ts
  src/common/modules/escrow/escrow.service.ts
  src/common/modules/escrow/models/deposit.entity.ts
  src/common/modules/escrow/utils/utils.ts
  src/listeners/ethereum-listener/ethereum-listener.handler.ts
  src/listeners/ethereum-listener/ethereum-listener.module.ts
  src/listeners/substrate-listener/commands/orders/order-cancelled/order-cancelled.handler.ts
  src/listeners/substrate-listener/commands/orders/order-failed/order-failed.handler.ts
  src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
  src/listeners/substrate-listener/substrate-listener.module.ts
  test/unit/common/modules/escrow/escrow.service.spec.ts
  test/unit/listeners/ethereum-listener/ethereum-listener.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-cancelled/order-cancelled.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-failed/order-failed.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.spec.ts
  test/unit/mock.ts
Labels: refactor

#252 [DBIO-1629] [Unit Test] Endpoint/SubstrateEndpoint ServiceRequest Methods
  test/unit/endpoints/substrate-endpoint/substrate-endpoint.controller.spec.ts
Labels: tests

#227 [DBIO-1485, DBIO-1305 & DBIO-1255] Enhance Email
  src/app.module.ts
  src/common/modules/caches/caches.service.ts
  src/common/modules/database/email-notification/email-notification.entity.ts
  src/common/modules/database/email-notification/email-notification.module.ts
  src/common/modules/database/email-notification/email-notification.service.ts
  src/common/modules/database/email-notification/index.ts
  src/common/modules/database/index.ts
  src/common/modules/index.ts
  src/common/modules/mailer/dto/email-notification.dto.ts
  src/common/modules/mailer/mailer.manager.ts
  src/common/modules/mailer/models/lab-register.model/service.ts
  src/endpoints/email/email.controller.ts
  src/endpoints/email/email.module.ts
  src/schedulers/mailer/mailer.service.ts
  src/schedulers/schedulers.module.ts
Labels: enhancement

#253 [DBIO-1608] [Unit Testing] Listener/ServiceEvent
  test/unit/listeners/substrate-listener/commands/services/service-created/service-created.command.spec.ts
  test/unit/listeners/substrate-listener/commands/services/service-created/service-created.handler.spec.ts
Labels: tests

#254 [DBIO-1339] feat : Create new column transaction_hash in table transaction_logs
  src/app.module.ts
  src/endpoints/transaction/transaction.module.ts
  src/listeners/substrate-listener/commands/service-request/service-request-waiting-for-unstaked/service-request-waiting-for-unstaked.handler.ts
  test/unit/endpoints/substrate-endpoint/services/service-request.service.spec.ts
  test/unit/endpoints/substrate-endpoint/substrate-endpoint.controller.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-cancelled/order-cancelled.command.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-cancelled/order-cancelled.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-created/order-created.command.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-created/order-created.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-failed/order-failed.command.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-failed/order-failed.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.command.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-paid/order-paid.command.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-paid/order-paid.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-refunded/order-refunded.command.spec.ts
  test/unit/listeners/substrate-listener/commands/orders/order-refunded/order-refunded.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-created/service-request-created.command.spec.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-created/service-request-created.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-processed/service-request-processed.command.spec.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-unstaked/service-request-unstaked.command.spec.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-unstaked/service-request-unstaked.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-wating-for-unstaked/service-request-waiting-for-unstaked.command.spec.ts
  test/unit/listeners/substrate-listener/commands/service-request/service-request-wating-for-unstaked/service-request-wating-for-unstaked.handler.spec.ts
  test/unit/mock.ts
Labels: enhancement

#255 Improve deployment resource request
  .github/workflows/deploy.yml
Labels: CI
