Repository debionetwork/debio-backend, pull requests merged in 2022-03, with the labels that each got.

#281 ci: fix deployment arguments
  .github/workflows/deploy.yml
Labels: ci

#284 bug fixing API substrate/customer/:customer_id
  package-lock.json
  src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
  test/unit/endpoints/substrate-endpoint/substrate-endpoint.controller.spec.ts
Labels: fix, test

#287 ci: optimize deployment resource request & limit
  .github/workflows/deploy.yml
Labels: ci

#289 [DBIO-2177] feat : Enhance API GET /substrate/orders/list/{customer_id}
  src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
  test/unit/endpoints/substrate-endpoint/substrate-endpoint.controller.spec.ts
Labels: feature, test

#292 feat: git hooks
  .maintain/install-hooks.sh
  package.json
  src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
  test/unit/@polkadot-api.mock.ts.ts
  test/unit/endpoints/substrate-endpoint/substrate-endpoint.controller.spec.ts
  test/unit/listeners/substrate-listener/substrate-listener.mock.data.ts
Labels: fix, improvement, test

#295 [DBIO-2223] ci: google auth with workload identity federation
  .github/workflows/builder.yml
  .github/workflows/deploy.yml
  .github/workflows/tester.yml
Labels: ci

#296 ci: optimize deployment resouces request
  .github/workflows/deploy.yml
Labels: ci

#299 tests: scheduler integration testing and elasticsearch docker compose
  package-lock.json
  package.json
  src/common/modules/mailer/models/lab-register.model/index.ts
  src/common/modules/substrate/substrate.service.ts
  src/common/modules/transaction-logging/transaction-logging.service.ts
  src/endpoints/health/health.controller.ts
  src/endpoints/recaptcha/recaptcha.controller.ts
  src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-fulfilled/genetic-analysis-order-fulfilled.command.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-fulfilled/genetic-analysis-order-fulfilled.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-paid/genetic-analysis-order-paid.command.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-paid/genetic-analysis-order-paid.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-refunded/genetic-analysis-order-refunded.command.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-refunded/genetic-analysis-order-refunded.handler.ts
  src/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysys-order-created/genetic-analysis-order-created.command.ts
  src/listeners/substrate-listener/commands/orders/order-cancelled/order-cancelled.handler.ts
  src/listeners/substrate-listener/commands/orders/order-created/order-created.handler.ts
  src/listeners/substrate-listener/commands/orders/order-fulfilled/order-fulfilled.handler.ts
  src/listeners/substrate-listener/commands/orders/order-paid/order-paid.handler.ts
  src/listeners/substrate-listener/commands/orders/order-refunded/order-refunded.handler.ts
  src/schedulers/mailer/mailer.service.ts
  test/e2e/config.ts
  test/e2e/docker-compose.yml
  test/e2e/elasticsearch-fixture.ts
  test/e2e/endpoints/cloud-storage.spec.ts
  test/e2e/endpoints/health.spec.ts
  test/e2e/endpoints/location.spec.ts
  test/e2e/endpoints/recaptcha.spec.ts
  test/e2e/endpoints/substrate-endpoint.spec.ts
  test/e2e/endpoints/verification.spec.ts
  test/e2e/fixture.ts
  test/e2e/schedulers/mailer.spec.ts
  test/e2e/setup.ts
  test/e2e/substrate-fixture.ts
  test/mocks/models/genetic-analysts/genetic-analysis-orders.mock.ts
  test/mocks/models/genetic-analysts/genetic-analysis.mock.ts
  test/mocks/models/genetic-analysts/genetic-analyst-qualifications.mock.ts
  test/mocks/models/genetic-analysts/genetic-analyst-service.mock.ts
  test/mocks/models/genetic-analysts/genetic-analysts.mock.ts
  test/mocks/models/genetic-analysts/genetic-data.mock.ts
  test/mocks/models/labs/certifications.mock.ts
  test/mocks/models/labs/genetic-testing.mock.ts
  test/mocks/models/labs/labs.mock.ts
  test/mocks/models/labs/orders.mock.ts
  test/mocks/models/labs/services.mock.ts
  test/unit/@polkadot-api.mock.ts.ts
  test/unit/common/modules/mailer/mailer.mock.data.ts
  test/unit/common/modules/substrate/substrate.service.spec.ts
  test/unit/endpoints/health/health.controller.spec.ts
  test/unit/endpoints/substrate-endpoint/substrate-endpoint.controller.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-created/genetic-anaysis-order-created.command.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-fulfilled/genetic-anaysis-order-fulfilled.command.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-paid/genetic-anaysis-order-paid.command.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analysis-order/genetic-analysis-order-refunded/genetic-anaysis-order-refunded.command.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analyst/genetic-analyst-staked/genetic-analyst-staked.handler.spec.ts
  test/unit/listeners/substrate-listener/commands/genetic-analyst/genetic-analyst-verification-status/genetic-analyst-verification-status.handler.spec.ts
Labels: fix, improvement, test

#297 [DBIO-2177] Enhance API GET /substrate/orders/list/{customer_id}
  package-lock.json
  src/endpoints/substrate-endpoint/services/genetic-analysis-order.service.ts
  src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
  test/unit/endpoints/substrate-endpoint/services/genetic-analysis-order-service.spec.ts
  test/unit/endpoints/substrate-endpoint/substrate-endpoint.controller.spec.ts
  test/unit/mock.ts
Labels: feature, improvement

#300 [DBIO-1452 & DBIO-1834] Quality controll
  package-lock.json
  src/endpoints/substrate-endpoint/dto/wallet-binding.dto.ts
  src/listeners/substrate-listener/commands/orders/order-failed/order-failed.handler.ts
Labels: feature, test
