Repository debionetwork/debio-backend, pull requests merged in 2022-09, with the labels that each got.

#439 ref: substrate endpoint labs
  src/endpoints/substrate-endpoint/services/lab.service.ts
  src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
  test/unit/endpoints/substrate-endpoint/services/lab.service.spec.ts
Labels: improvement

#424 feat: Email ga regristration
  notes.ts.txt
  src/common/modules/mailer/mailer.manager.ts
  src/common/modules/mailer/models/genetic-analyst-register.model/index.ts
  src/common/modules/mailer/models/genetic-analyst-register.model/service.ts
  src/common/modules/mailer/models/index.ts
  src/common/modules/mailer/templates/genetic-analyst-register.hbs
  src/endpoints/email/email.controller.ts
  src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
Labels: feature

#440 ci: improve docker builder smaller size
  .dockerignore
  .maintain/docker/Dockerfile
  package-lock.json
Labels: ci

#442 ci: improvement
  .github/CODEOWNERS
  .github/pull_request_template.md
  .github/workflows/analyzer.yaml
  .github/workflows/builder.yaml
  .github/workflows/builder.yml
  .github/workflows/deploy.yml
  .github/workflows/deployer.yaml
  .github/workflows/mlc_config.json
  .github/workflows/rcb_config.json
  .github/workflows/releaser.yaml
  .github/workflows/tester.yaml
  .github/workflows/tester.yml
  .maintain/docker/docker-compose.yml
  README.md
  babel.config.js
  package.json
  src/endpoints/verification/verification.service.ts
  test/e2e/endpoints/recaptcha.spec.ts
  test/e2e/setup.ts
  test/e2e/teardown.ts
  test/unit/common/modules/proxies/process-env.proxy.set-default.spec.ts
  test/unit/endpoints/recaptcha/recaptcha.controller.spec.ts
  test/unit/endpoints/substrate-endpoint/substrate-endpoint.controller.spec.ts
  test/unit/endpoints/verification/verification.service.spec.ts
Labels: ci

#443 ci: remove secrets
  .github/workflows/deployer.yaml
Labels: ci

#444 ci: bump scorecard to v2
  .github/dependabot.yaml
  .github/pull_request_template.md
  .github/workflows/analyzer.yaml
Labels: ci

#447 ci: fixed release auth workflow
  .github/workflows/releaser.yaml
Labels: ci

#448 ci: fix changelog builder credentials
  .github/workflows/releaser.yaml
Labels: ci

#450 ci: fixed docker builder
  .github/pull_request_template.md
  .github/workflows/builder.yaml
  .github/workflows/mlc_config.json
Labels: ci

#449 fix: API /email/registered-genetic-analyst/{genetic_analyst_id} for send email to DAOGenics
  src/endpoints/email/email.controller.ts
  test/e2e/endpoints/email.spec.ts
Labels: fix

#441 fix: update order from updated to created
  src/common/modules/notification/notification.service.ts
Labels: fix

#451 ci: cleanup ssh tunneling
  .github/workflows/deployer.yaml
  README.md
Labels: ci

#452 ci: fix deployer cors allow origin
  .github/workflows/deployer.yaml
Labels: ci

#453 fix: remove process.env and change to gcloud secret manager
  src/endpoints/email/email.controller.ts
Labels: fix

#454 ci: allow all origin on testnet
  .github/workflows/deployer.yaml
Labels: ci
