Repository debionetwork/debio-backend, pull requests merged in 2022-10, with the labels that each got.

#456 fix: genetic analyst register template and data object
  src/common/modules/mailer/mailer.manager.ts
  src/common/modules/mailer/models/genetic-analyst-register.model/index.ts
  src/common/modules/mailer/templates/genetic-analyst-register.hbs
Labels: fix

#462 ci: improvements
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE.md
  .github/dependabot.yaml
  .github/pull_request_template.md
  .github/workflows/analyzer.yaml
  .github/workflows/builder.yaml
  .github/workflows/cicd.yaml
  .github/workflows/cii.yaml
  .github/workflows/deployer.yaml
  .github/workflows/mlc_config.json
  .github/workflows/rcb_config.json
  .github/workflows/releaser.yaml
  .github/workflows/sast.yaml
  .github/workflows/tester.yaml
  .maintain/docker/Dockerfile
  .maintain/install-hooks.sh
  CODEOWNERS
  README.md
  package.json
Labels: ci

#457 feat: add region and country full state name
  src/endpoints/substrate-endpoint/services/lab.service.ts
  test/unit/endpoints/substrate-endpoint/services/lab.service.spec.ts
Labels: feature

#472 fix: lab substrate api
  src/endpoints/substrate-endpoint/services/lab.service.ts
Labels: fix

#475 fix: lab service not show
  src/endpoints/substrate-endpoint/services/lab.service.ts
Labels: fix

#481 feat: move conversion to backend
  package-lock.json
  package.json
  src/app.module.ts
  src/common/modules/debio-conversion/debio-conversion.module.ts
  src/common/modules/debio-conversion/debio-conversion.service.ts
  src/common/modules/debio-conversion/models/exchange.ts
  src/common/secrets/index.ts
  src/endpoints/conversion/conversion.controller.ts
  src/endpoints/conversion/conversion.module.ts
  src/endpoints/substrate-endpoint/services/service-request.service.ts
  test/e2e/docker-compose.yml
  test/e2e/endpoints/authentication.spec.ts
  test/e2e/endpoints/bounty.spec.ts
  test/e2e/endpoints/cloud-storage.spec.ts
  test/e2e/endpoints/email.spec.ts
  test/e2e/endpoints/health.spec.ts
  test/e2e/endpoints/recaptcha.spec.ts
  test/e2e/endpoints/substrate-endpoint.spec.ts
  test/e2e/endpoints/transaction.spec.ts
  test/e2e/endpoints/verification.spec.ts
  test/e2e/setup.ts
  test/unit/common/modules/debio-conversion/debio-conversion.service.spec.ts
  test/unit/endpoints/substrate-endpoint/services/service-request.service.spec.ts
  test/unit/mock.ts
Labels: improvement

#482 improvement: update getCache controller
  .env-template
  src/common/modules/debio-conversion/debio-conversion.service.ts
  src/endpoints/conversion/conversion.controller.ts
Labels: improvement

#483 fix: env and genetic analyst register template
  src/common/modules/debio-conversion/debio-conversion.service.ts
  src/common/modules/mailer/mailer.manager.ts
  src/common/modules/mailer/templates/genetic-analyst-register.hbs
  src/common/secrets/index.ts
  src/endpoints/conversion/conversion.controller.ts
  src/endpoints/email/email.controller.ts
Labels: fix

#484 feat: endpoint menstrual calendar
  src/endpoints/substrate-endpoint/services/index.ts
  src/endpoints/substrate-endpoint/services/menstrual-calendar.service.ts
  src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
  src/endpoints/substrate-endpoint/substrate-endpoint.module.ts
  test/unit/endpoints/substrate-endpoint/substrate-endpoint.controller.spec.ts
Labels: feature

#476 feat: Pinata endpoint
  .env-template
  notes.ts.txt
  package-lock.json
  package.json
  src/app.module.ts
  src/common/secrets/index.ts
  src/endpoints/authentication/authentication.controller.ts
  src/endpoints/authentication/authentication.module.ts
  src/endpoints/authentication/pinata-jwt.model.ts
  src/endpoints/pinata/pinata.controller.ts
  src/endpoints/pinata/pinata.module.ts
  src/endpoints/pinata/pinata.service.ts
  test/e2e/endpoints/authentication.spec.ts
  test/unit/endpoints/authentication/authentication.controller.spec.ts
Labels: feature
