Repository debionetwork/debio-backend, pull requests merged in 2023-02, with the labels that each got.

#576 fix: menstrual subscription list
  src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
Labels: fix

#577 fix: endpoint for menstrual subscription
  src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
Labels: fix

#578 fix: move menstrual subscription endpoint
  src/endpoints/substrate-endpoint/substrate-endpoint.controller.ts
Labels: fix

#579 feat: health professional registrations
  src/common/modules/mailer/mailer.manager.ts
  src/common/modules/mailer/models/health-professional.model/index.ts
  src/common/modules/mailer/models/index.ts
  src/common/modules/mailer/templates/health-professional-register.hbs
  src/common/modules/polkadot-provider/index.ts
  src/common/modules/polkadot-provider/query/health-professional.ts
  src/endpoints/email/email.controller.ts
  src/endpoints/verification/verification.controller.ts
  src/endpoints/verification/verification.module.ts
  src/endpoints/verification/verification.service.ts
  test/e2e/endpoints/verification.spec.ts
  test/unit/endpoints/verification/verification.service.spec.ts
  test/unit/jest-unit.json
Labels: feature

#581 fix: fix currency
  src/common/modules/mailer/mailer.manager.ts
  src/common/modules/mailer/models/currency.ts
  src/common/modules/mailer/models/genetic-analyst-register.model/service.ts
  src/common/modules/mailer/models/health-professional.model/index.ts
  src/common/modules/mailer/models/lab-register.model/service.ts
  src/common/modules/mailer/templates/health-professional-register.hbs
Labels: fix

#582 fix: verified hp
  src/common/modules/mailer/models/genetic-analyst-register.model/service.ts
  src/common/modules/mailer/models/lab-register.model/service.ts
  src/endpoints/myriad/myriad.module.ts
  src/endpoints/verification/dto/health-professional.dto.ts
  src/endpoints/verification/verification.controller.ts
  src/endpoints/verification/verification.module.ts
  src/endpoints/verification/verification.service.ts
  test/unit/endpoints/verification/verification.service.spec.ts
Labels: fix

#583 fix: conversion
  package-lock.json
  package.json
  src/common/modules/debio-conversion/debio-conversion.service.ts
Labels: fix, feature

#517 chore(main): release 2.4.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#592 fix: update auth login myriad
  src/endpoints/myriad/interface/auth-user.ts
  src/endpoints/myriad/myriad.service.ts
Labels: improvement

#593 chore(main): release 2.4.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending
